ANIMA: animaFibersApplyTransformSerie.cxx File Reference
animaFibersApplyTransformSerie.cxx File Reference
#include <tclap/CmdLine.h>
#include <animaTransformSeriesReader.h>
#include <animaFibersReader.h>
#include <animaFibersWriter.h>
#include <vtkPolyData.h>
#include <vtkGenericCell.h>
Classes
struct ThreaderArguments
Functions
void ApplyTransformToTracks (vtkPolyData *tracks, unsigned int startIndex, unsigned int endIndex, anima::TransformSeriesReader< double, 3 >::OutputTransformType *transform)
int main (int ac, const char **av)
ITK_THREAD_RETURN_TYPE ThreadTransformApplyer (void *arg)
Function Documentation
void ApplyTransformToTracks (vtkPolyData * tracks, unsigned int startIndex, unsigned int endIndex, anima::TransformSeriesReader< double, 3 >::OutputTransformType * transform)
Definition at line 9 of file animaFibersApplyTransformSerie.cxx.
Referenced by ThreadTransformApplyer().
int main (int ac, const char ** av)
Definition at line 66 of file animaFibersApplyTransformSerie.cxx.
References anima::FibersReader::GetOutput(), anima::TransformSeriesReader< TScalarType, NDimensions >::GetOutputTransform(), anima::FibersReader::SetFileName(), anima::FibersWriter::SetFileName(), anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput(), anima::FibersWriter::SetInputData(), ThreadTransformApplyer(), ThreaderArguments::tracks, ThreaderArguments::transformation, anima::FibersReader::Update(), and anima::FibersWriter::Update().
ITK_THREAD_RETURN_TYPE ThreadTransformApplyer (void * arg)
Definition at line 45 of file animaFibersApplyTransformSerie.cxx.
References ApplyTransformToTracks(), ThreaderArguments::tracks, and ThreaderArguments::transformation.
Referenced by main().