ANIMA: animaLocalPatchCovarianceDistance.cxx File Reference
animaLocalPatchCovarianceDistance.cxx File Reference
#include <iostream>
#include <tclap/CmdLine.h>
#include <animaReadWriteFunctions.h>
#include <animaLocalPatchCovarianceDistanceImageFilter.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char **argv)
Function Documentation
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 8 of file animaLocalPatchCovarianceDistance.cxx.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 14 of file animaLocalPatchCovarianceDistance.cxx.
References eventCallback(), anima::readImage(), and anima::writeImage().