ANIMA: anima::GaussianMCMCostFunction Class Reference
anima::GaussianMCMCostFunction Class Reference
#include <animaGaussianMCMCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef GaussianMCMCostFunction Self
typedef BaseMCMCostFunction Superclass
Public Types inherited from anima::BaseMCMCostFunction
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef MCMType::ListType ListType
typedef MCMType::Pointer MCMPointer
typedef anima::MultiCompartmentModel MCMType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef BaseMCMCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
typedef MCMType::Vector3DType Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetMarginalEstimation (bool _arg)
Public Member Functions inherited from anima::BaseMCMCostFunction
virtual double GetB0Value ()
MCMPointer & GetMCMStructure ()
virtual unsigned int GetNumberOfParameters () const ITK_OVERRIDE
Returns number of optimized parameters.
virtual double GetSigmaSquare ()
void SetBValues (ListType &value)
void SetGradients (std::vector< Vector3DType > &value)
void SetMCMStructure (MCMType *model)
void SetObservedSignals (ListType &value)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
GaussianMCMCostFunction ()
void GetMarginalDerivative (DerivativeType &derivative) const
void GetProfileDerivative (DerivativeType &derivative) const
virtual ~GaussianMCMCostFunction ()
Protected Member Functions inherited from anima::BaseMCMCostFunction
BaseMCMCostFunction ()
virtual ~BaseMCMCostFunction ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseMCMCostFunction
double m_B0Value
ListType m_BValues
std::vector< Vector3DType > m_Gradients
MCMPointer m_MCMStructure
ListType m_ObservedSignals
std::vector< double > m_PredictedSignals
double m_SigmaSquare
ListType m_TestedParameters
bool m_UpdatedInputs
Detailed Description
Definition at line 11 of file animaGaussianMCMCostFunction.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::GaussianMCMCostFunction::ConstPointer
Definition at line 18 of file animaGaussianMCMCostFunction.h.
typedef Superclass::DerivativeType anima::GaussianMCMCostFunction::DerivativeType
Definition at line 26 of file animaGaussianMCMCostFunction.h.
typedef Superclass::MeasureType anima::GaussianMCMCostFunction::MeasureType
Definition at line 25 of file animaGaussianMCMCostFunction.h.
typedef Superclass::ParametersType anima::GaussianMCMCostFunction::ParametersType
Definition at line 27 of file animaGaussianMCMCostFunction.h.
typedef itk::SmartPointer<Self> anima::GaussianMCMCostFunction::Pointer
Definition at line 17 of file animaGaussianMCMCostFunction.h.
typedef GaussianMCMCostFunction anima::GaussianMCMCostFunction::Self
Standard class typedefs.
Definition at line 15 of file animaGaussianMCMCostFunction.h.
typedef BaseMCMCostFunction anima::GaussianMCMCostFunction::Superclass
Definition at line 16 of file animaGaussianMCMCostFunction.h.
Constructor & Destructor Documentation
anima::GaussianMCMCostFunction::GaussianMCMCostFunction () inline protected
Definition at line 36 of file animaGaussianMCMCostFunction.h.
virtual anima::GaussianMCMCostFunction::~GaussianMCMCostFunction () inline protected virtual
Definition at line 41 of file animaGaussianMCMCostFunction.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::GaussianMCMCostFunction::CreateAnother (void) const
void anima::GaussianMCMCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Reimplemented from anima::BaseMCMCostFunction.
Definition at line 65 of file animaGaussianMCMCostFunction.cxx.
References GetMarginalDerivative(), GetProfileDerivative(), and anima::BaseMCMCostFunction::m_TestedParameters.
void anima::GaussianMCMCostFunction::GetMarginalDerivative (DerivativeType & derivative) const protected
Definition at line 100 of file animaGaussianMCMCostFunction.cxx.
References anima::BaseMCMCostFunction::m_B0Value, anima::BaseMCMCostFunction::m_BValues, anima::BaseMCMCostFunction::m_Gradients, anima::BaseMCMCostFunction::m_MCMStructure, anima::BaseMCMCostFunction::m_ObservedSignals, anima::BaseMCMCostFunction::m_PredictedSignals, and anima::BaseMCMCostFunction::m_SigmaSquare.
Referenced by GetDerivative().
virtual const char* anima::GaussianMCMCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseMCMCostFunction.
void anima::GaussianMCMCostFunction::GetProfileDerivative (DerivativeType & derivative) const protected
Definition at line 124 of file animaGaussianMCMCostFunction.cxx.
References anima::BaseMCMCostFunction::m_B0Value, anima::BaseMCMCostFunction::m_BValues, anima::BaseMCMCostFunction::m_Gradients, anima::BaseMCMCostFunction::m_MCMStructure, anima::BaseMCMCostFunction::m_ObservedSignals, anima::BaseMCMCostFunction::m_PredictedSignals, and anima::BaseMCMCostFunction::m_SigmaSquare.
Referenced by GetDerivative().
GaussianMCMCostFunction::MeasureType anima::GaussianMCMCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 10 of file animaGaussianMCMCostFunction.cxx.
References anima::BaseMCMCostFunction::m_B0Value, anima::BaseMCMCostFunction::m_BValues, anima::BaseMCMCostFunction::m_Gradients, anima::BaseMCMCostFunction::m_MCMStructure, anima::BaseMCMCostFunction::m_ObservedSignals, anima::BaseMCMCostFunction::m_PredictedSignals, anima::BaseMCMCostFunction::m_SigmaSquare, and anima::BaseMCMCostFunction::m_TestedParameters.
static Pointer anima::GaussianMCMCostFunction::New () static
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction().
virtual void anima::GaussianMCMCostFunction::SetMarginalEstimation (bool _arg) virtual
The documentation for this class was generated from the following files:
animaGaussianMCMCostFunction.h
animaGaussianMCMCostFunction.cxx