ANIMA: anima::TensorCompartment Class Reference
anima::TensorCompartment Class Reference
#include <animaTensorCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef TensorCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
double GetAxialDiffusivity () ITK_OVERRIDE
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
double GetOrientationPhi () ITK_OVERRIDE
double GetOrientationTheta () ITK_OVERRIDE
virtual ListType GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType GetParametersAsVector () ITK_OVERRIDE
virtual ListType GetParameterUpperBounds () ITK_OVERRIDE
double GetPerpendicularAngle () ITK_OVERRIDE
double GetRadialDiffusivity1 () ITK_OVERRIDE
double GetRadialDiffusivity2 () ITK_OVERRIDE
virtual ListType GetSignalAttenuationJacobian (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform) ITK_OVERRIDE
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
void SetAxialDiffusivity (double num) ITK_OVERRIDE
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateDiffusivities (bool arg)
void SetOrientationPhi (double num) ITK_OVERRIDE
void SetOrientationTheta (double num) ITK_OVERRIDE
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
void SetPerpendicularAngle (double num) ITK_OVERRIDE
void SetRadialDiffusivity1 (double num) ITK_OVERRIDE
void SetRadialDiffusivity2 (double num) ITK_OVERRIDE
void UpdateParametersFromTensor ()
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
std::vector< double > & GetBoundedSignVector ()
double GetBoundedSignVectorValue (unsigned int i)
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
double GetPredictedSignal (double bValue, const Vector3DType &gradient)
bool GetUseBoundedOptimization ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-6)
Tests equality to another compartment up to a constant.
void SetBoundedSignVectorValue (unsigned int i, double val)
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
void SetUseBoundedOptimization (bool x)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual ListType BoundParameters (const ListType &params) ITK_OVERRIDE
TensorCompartment ()
virtual void UnboundParameters (ListType &params) ITK_OVERRIDE
void UpdateAngleConfiguration ()
Update angles' sine and cosine values from parameters.
void UpdateDiffusionTensor ()
Update diffusion tensor value from parameters.
virtual ~TensorCompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
Static Protected Attributes inherited from anima::BaseCompartment
static const double m_AzimuthAngleUpperBound = 2.0 * M_PI
static const double m_DefaultConcentrationUpperBound = 20
static const double m_DiffusivityLowerBound = 1e-5
static const double m_DiffusivityUpperBound = 3e-3
static const double m_Epsilon = 1.0e-2
static const double m_PolarAngleUpperBound = M_PI
static const double m_RadialDiffusivityUpperBound = 1e-3
static const unsigned int m_SpaceDimension = 3
static const double m_ZeroLowerBound = 0.0
Detailed Description
Definition at line 10 of file animaTensorCompartment.h.
Member Typedef Documentation
typedef Superclass::Pointer anima::TensorCompartment::BasePointer
Definition at line 16 of file animaTensorCompartment.h.
typedef itk::SmartPointer<const Self> anima::TensorCompartment::ConstPointer
Definition at line 18 of file animaTensorCompartment.h.
typedef Superclass::Matrix3DType anima::TensorCompartment::Matrix3DType
Definition at line 21 of file animaTensorCompartment.h.
typedef Superclass::ModelOutputVectorType anima::TensorCompartment::ModelOutputVectorType
Definition at line 19 of file animaTensorCompartment.h.
typedef itk::SmartPointer<Self> anima::TensorCompartment::Pointer
Definition at line 17 of file animaTensorCompartment.h.
typedef TensorCompartment anima::TensorCompartment::Self
Definition at line 14 of file animaTensorCompartment.h.
typedef BaseCompartment anima::TensorCompartment::Superclass
Definition at line 15 of file animaTensorCompartment.h.
typedef Superclass::Vector3DType anima::TensorCompartment::Vector3DType
Definition at line 20 of file animaTensorCompartment.h.
Constructor & Destructor Documentation
anima::TensorCompartment::TensorCompartment () inline protected
Definition at line 71 of file animaTensorCompartment.h.
virtual anima::TensorCompartment::~TensorCompartment () inline protected virtual
Definition at line 82 of file animaTensorCompartment.h.
Member Function Documentation
TensorCompartment::ListType anima::TensorCompartment::BoundParameters (const ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 289 of file animaTensorCompartment.cxx.
References anima::mcm_utilities::ComputeBoundedValue(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_RadialDiffusivityUpperBound, anima::BaseCompartment::m_ZeroLowerBound, and anima::BaseCompartment::SetBoundedSignVectorValue().
Referenced by SetParametersFromVector().
virtual::itk::LightObject::Pointer anima::TensorCompartment::CreateAnother (void) const
double anima::TensorCompartment::GetAxialDiffusivity () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 176 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and UpdateParametersFromTensor().
Referenced by GetFractionalAnisotropy(), GetParametersAsVector(), GetSignalAttenuationJacobian(), SetAxialDiffusivity(), and UpdateDiffusionTensor().
unsigned int anima::TensorCompartment::GetCompartmentSize () virtual
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implements anima::BaseCompartment.
Definition at line 417 of file animaTensorCompartment.cxx.
Referenced by GetCompartmentVector(), GetNumberOfParameters(), Reorient(), and SetCompartmentVector().
DiffusionModelCompartmentType anima::TensorCompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 29 of file animaTensorCompartment.h.
References anima::Tensor.
TensorCompartment::ModelOutputVectorType & anima::TensorCompartment::GetCompartmentVector () virtual
Get compartment overall description vector, mainly for writing, should be self-contained.
Implements anima::BaseCompartment.
Definition at line 436 of file animaTensorCompartment.cxx.
References GetCompartmentSize(), anima::GetVectorRepresentation(), anima::BaseCompartment::m_CompartmentVector, and UpdateDiffusionTensor().
const TensorCompartment::Matrix3DType & anima::TensorCompartment::GetDiffusionTensor () virtual
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented from anima::BaseCompartment.
Definition at line 476 of file animaTensorCompartment.cxx.
References UpdateDiffusionTensor().
double anima::TensorCompartment::GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 9 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::m_SpaceDimension, and UpdateDiffusionTensor().
Referenced by GetSignalAttenuationJacobian().
double anima::TensorCompartment::GetFractionalAnisotropy () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 537 of file animaTensorCompartment.cxx.
References GetAxialDiffusivity(), GetRadialDiffusivity1(), and GetRadialDiffusivity2().
double anima::TensorCompartment::GetLogDiffusionProfile (const Vector3DType & sample) virtual
Implements anima::BaseCompartment.
Definition at line 99 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::m_SpaceDimension, and UpdateDiffusionTensor().
virtual const char* anima::TensorCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseCompartment.
unsigned int anima::TensorCompartment::GetNumberOfParameters () virtual
Number of optimized parameters: smaller than total number of parameters.
Implements anima::BaseCompartment.
Definition at line 422 of file animaTensorCompartment.cxx.
References GetCompartmentSize().
Referenced by GetParameterLowerBounds(), GetParametersAsVector(), GetParameterUpperBounds(), GetSignalAttenuationJacobian(), and SetParametersFromVector().
double anima::TensorCompartment::GetOrientationPhi () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 145 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::GetOrientationPhi(), and UpdateParametersFromTensor().
Referenced by GetParametersAsVector(), GetSignalAttenuationJacobian(), SetOrientationPhi(), and UpdateAngleConfiguration().
double anima::TensorCompartment::GetOrientationTheta () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 129 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::GetOrientationTheta(), and UpdateParametersFromTensor().
Referenced by GetParametersAsVector(), GetSignalAttenuationJacobian(), SetOrientationTheta(), and UpdateAngleConfiguration().
TensorCompartment::ListType anima::TensorCompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 261 of file animaTensorCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_DiffusivityLowerBound, and anima::BaseCompartment::m_ZeroLowerBound.
TensorCompartment::ListType anima::TensorCompartment::GetParametersAsVector () virtual
Implements anima::BaseCompartment.
Definition at line 240 of file animaTensorCompartment.cxx.
References GetAxialDiffusivity(), GetNumberOfParameters(), GetOrientationPhi(), GetOrientationTheta(), GetPerpendicularAngle(), GetRadialDiffusivity1(), GetRadialDiffusivity2(), anima::BaseCompartment::GetUseBoundedOptimization(), and UnboundParameters().
TensorCompartment::ListType anima::TensorCompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 271 of file animaTensorCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, and anima::BaseCompartment::m_RadialDiffusivityUpperBound.
double anima::TensorCompartment::GetPerpendicularAngle () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 161 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::GetPerpendicularAngle(), and UpdateParametersFromTensor().
Referenced by GetParametersAsVector(), GetSignalAttenuationJacobian(), SetPerpendicularAngle(), and UpdateAngleConfiguration().
double anima::TensorCompartment::GetRadialDiffusivity1 () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 191 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::GetRadialDiffusivity1(), and UpdateParametersFromTensor().
Referenced by GetFractionalAnisotropy(), GetParametersAsVector(), GetSignalAttenuationJacobian(), SetRadialDiffusivity1(), and UpdateDiffusionTensor().
double anima::TensorCompartment::GetRadialDiffusivity2 () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 206 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::GetRadialDiffusivity2(), and UpdateParametersFromTensor().
Referenced by GetFractionalAnisotropy(), GetParametersAsVector(), GetSignalAttenuationJacobian(), SetRadialDiffusivity2(), and UpdateDiffusionTensor().
TensorCompartment::ListType anima::TensorCompartment::GetSignalAttenuationJacobian (double bValue, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 25 of file animaTensorCompartment.cxx.
References anima::mcm_utilities::BoundedDerivativeAddOn(), anima::ComputeScalarProduct(), GetAxialDiffusivity(), anima::BaseCompartment::GetBoundedSignVectorValue(), GetFourierTransformedDiffusionProfile(), GetNumberOfParameters(), GetOrientationPhi(), GetOrientationTheta(), GetPerpendicularAngle(), GetRadialDiffusivity1(), GetRadialDiffusivity2(), anima::BaseCompartment::GetUseBoundedOptimization(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_RadialDiffusivityUpperBound, anima::BaseCompartment::m_ZeroLowerBound, and UpdateDiffusionTensor().
static Pointer anima::TensorCompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
void anima::TensorCompartment::Reorient (vnl_matrix< double > & orientationMatrix, bool affineTransform) virtual
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
Reimplemented from anima::BaseCompartment.
Definition at line 447 of file animaTensorCompartment.cxx.
References anima::ExtractPPDRotationFromJacobianMatrix(), GetCompartmentSize(), anima::GetVectorRepresentation(), anima::RotateSymmetricMatrix(), SetCompartmentVector(), and UpdateDiffusionTensor().
void anima::TensorCompartment::SetAxialDiffusivity (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 167 of file animaTensorCompartment.cxx.
References GetAxialDiffusivity(), and anima::BaseCompartment::SetAxialDiffusivity().
Referenced by SetParametersFromVector(), and UpdateParametersFromTensor().
void anima::TensorCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) virtual
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implements anima::BaseCompartment.
Definition at line 337 of file animaTensorCompartment.cxx.
References GetCompartmentSize(), anima::GetTensorFromVectorRepresentation(), anima::GetTensorPower(), and anima::BaseCompartment::m_SpaceDimension.
Referenced by Reorient().
void anima::TensorCompartment::SetEstimateDiffusivities (bool arg)
Definition at line 328 of file animaTensorCompartment.cxx.
void anima::TensorCompartment::SetOrientationPhi (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 135 of file animaTensorCompartment.cxx.
References GetOrientationPhi(), and anima::BaseCompartment::SetOrientationPhi().
Referenced by SetParametersFromVector(), and UpdateParametersFromTensor().
void anima::TensorCompartment::SetOrientationTheta (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 119 of file animaTensorCompartment.cxx.
References GetOrientationTheta(), and anima::BaseCompartment::SetOrientationTheta().
Referenced by SetParametersFromVector(), and UpdateParametersFromTensor().
void anima::TensorCompartment::SetParametersFromVector (const ListType & params) virtual
Various methods for optimization parameters setting and getting.
Implements anima::BaseCompartment.
Definition at line 212 of file animaTensorCompartment.cxx.
References BoundParameters(), anima::BaseCompartment::GetBoundedSignVector(), GetNumberOfParameters(), anima::BaseCompartment::GetUseBoundedOptimization(), SetAxialDiffusivity(), SetOrientationPhi(), SetOrientationTheta(), SetPerpendicularAngle(), SetRadialDiffusivity1(), and SetRadialDiffusivity2().
void anima::TensorCompartment::SetPerpendicularAngle (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 151 of file animaTensorCompartment.cxx.
References GetPerpendicularAngle(), and anima::BaseCompartment::SetPerpendicularAngle().
Referenced by SetParametersFromVector(), and UpdateParametersFromTensor().
void anima::TensorCompartment::SetRadialDiffusivity1 (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 182 of file animaTensorCompartment.cxx.
References GetRadialDiffusivity1(), and anima::BaseCompartment::SetRadialDiffusivity1().
Referenced by SetParametersFromVector(), and UpdateParametersFromTensor().
void anima::TensorCompartment::SetRadialDiffusivity2 (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 197 of file animaTensorCompartment.cxx.
References GetRadialDiffusivity2(), and anima::BaseCompartment::SetRadialDiffusivity2().
Referenced by SetParametersFromVector(), and UpdateParametersFromTensor().
void anima::TensorCompartment::UnboundParameters (ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 314 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_RadialDiffusivityUpperBound, anima::BaseCompartment::m_ZeroLowerBound, and anima::mcm_utilities::UnboundValue().
Referenced by GetParametersAsVector().
void anima::TensorCompartment::UpdateAngleConfiguration () protected
Update angles' sine and cosine values from parameters.
Definition at line 514 of file animaTensorCompartment.cxx.
References GetOrientationPhi(), GetOrientationTheta(), and GetPerpendicularAngle().
Referenced by UpdateDiffusionTensor().
void anima::TensorCompartment::UpdateDiffusionTensor () protected
Update diffusion tensor value from parameters.
Definition at line 482 of file animaTensorCompartment.cxx.
References GetAxialDiffusivity(), GetRadialDiffusivity1(), GetRadialDiffusivity2(), anima::GetTensorPower(), anima::BaseCompartment::m_SpaceDimension, and UpdateAngleConfiguration().
Referenced by GetCompartmentVector(), GetDiffusionTensor(), GetFourierTransformedDiffusionProfile(), GetLogDiffusionProfile(), GetSignalAttenuationJacobian(), and Reorient().
void anima::TensorCompartment::UpdateParametersFromTensor ()
Definition at line 363 of file animaTensorCompartment.cxx.
References anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_SpaceDimension, SetAxialDiffusivity(), SetOrientationPhi(), SetOrientationTheta(), SetPerpendicularAngle(), SetRadialDiffusivity1(), SetRadialDiffusivity2(), and anima::TransformCartesianToSphericalCoordinates().
Referenced by GetAxialDiffusivity(), GetOrientationPhi(), GetOrientationTheta(), GetPerpendicularAngle(), GetRadialDiffusivity1(), and GetRadialDiffusivity2().
The documentation for this class was generated from the following files:
animaTensorCompartment.h
animaTensorCompartment.cxx