ANIMA: anima::ApproximateMCMSmoothingCostFunction Class Reference
anima::ApproximateMCMSmoothingCostFunction Class Reference
#include <animaApproximateMCMSmoothingCostFunction.h>
Public Types
typedef anima::BaseCompartment::Pointer BaseCompartmentPointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef MCModelType::Vector3DType GradientType
typedef anima::MultiCompartmentModel MCModelType
typedef MCModelType::Pointer MCMPointer
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef ApproximateMCMSmoothingCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
typedef anima::BaseCompartment::Vector3DType Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
void SetBValues (const std::vector< double > &val)
void SetBValueWeightIndexes (const std::vector< unsigned int > &val)
void SetGradientDirections (const std::vector< GradientType > &val)
void SetMovingModels (const std::vector< MCMPointer > &movingModels, const std::vector< GradientType > &gradients, const std::vector< double > &bValues)
virtual void SetParameterScale (double _arg)
void SetReferenceModels (const std::vector< MCMPointer > &refModels, const std::vector< GradientType > &gradients, const std::vector< double > &bValues)
void SetSphereWeights (const std::vector< double > &val)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
ApproximateMCMSmoothingCostFunction ()
virtual ~ApproximateMCMSmoothingCostFunction ()
Detailed Description
Definition at line 10 of file animaApproximateMCMSmoothingCostFunction.h.
Member Typedef Documentation
typedef anima::BaseCompartment::Pointer anima::ApproximateMCMSmoothingCostFunction::BaseCompartmentPointer
Definition at line 31 of file animaApproximateMCMSmoothingCostFunction.h.
typedef itk::SmartPointer<const Self> anima::ApproximateMCMSmoothingCostFunction::ConstPointer
Definition at line 17 of file animaApproximateMCMSmoothingCostFunction.h.
typedef Superclass::DerivativeType anima::ApproximateMCMSmoothingCostFunction::DerivativeType
Definition at line 25 of file animaApproximateMCMSmoothingCostFunction.h.
typedef MCModelType::Vector3DType anima::ApproximateMCMSmoothingCostFunction::GradientType
Definition at line 30 of file animaApproximateMCMSmoothingCostFunction.h.
typedef anima::MultiCompartmentModel anima::ApproximateMCMSmoothingCostFunction::MCModelType
Definition at line 28 of file animaApproximateMCMSmoothingCostFunction.h.
typedef MCModelType::Pointer anima::ApproximateMCMSmoothingCostFunction::MCMPointer
Definition at line 29 of file animaApproximateMCMSmoothingCostFunction.h.
typedef Superclass::MeasureType anima::ApproximateMCMSmoothingCostFunction::MeasureType
Definition at line 24 of file animaApproximateMCMSmoothingCostFunction.h.
typedef Superclass::ParametersType anima::ApproximateMCMSmoothingCostFunction::ParametersType
Definition at line 26 of file animaApproximateMCMSmoothingCostFunction.h.
typedef itk::SmartPointer<Self> anima::ApproximateMCMSmoothingCostFunction::Pointer
Definition at line 16 of file animaApproximateMCMSmoothingCostFunction.h.
typedef ApproximateMCMSmoothingCostFunction anima::ApproximateMCMSmoothingCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaApproximateMCMSmoothingCostFunction.h.
typedef itk::SingleValuedCostFunction anima::ApproximateMCMSmoothingCostFunction::Superclass
Definition at line 15 of file animaApproximateMCMSmoothingCostFunction.h.
typedef anima::BaseCompartment::Vector3DType anima::ApproximateMCMSmoothingCostFunction::Vector3DType
Definition at line 32 of file animaApproximateMCMSmoothingCostFunction.h.
Constructor & Destructor Documentation
anima::ApproximateMCMSmoothingCostFunction::ApproximateMCMSmoothingCostFunction () inline protected
Definition at line 53 of file animaApproximateMCMSmoothingCostFunction.h.
virtual anima::ApproximateMCMSmoothingCostFunction::~ApproximateMCMSmoothingCostFunction () inline protected virtual
Definition at line 60 of file animaApproximateMCMSmoothingCostFunction.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::ApproximateMCMSmoothingCostFunction::CreateAnother (void) const
void anima::ApproximateMCMSmoothingCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 132 of file animaApproximateMCMSmoothingCostFunction.cxx.
Referenced by GetValue().
virtual const char* anima::ApproximateMCMSmoothingCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
unsigned int anima::ApproximateMCMSmoothingCostFunction::GetNumberOfParameters () const inline
Definition at line 50 of file animaApproximateMCMSmoothingCostFunction.h.
ApproximateMCMSmoothingCostFunction::MeasureType anima::ApproximateMCMSmoothingCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 82 of file animaApproximateMCMSmoothingCostFunction.cxx.
References GetDerivative().
Referenced by SetSphereWeights().
static Pointer anima::ApproximateMCMSmoothingCostFunction::New () static
void anima::ApproximateMCMSmoothingCostFunction::SetBValues (const std::vector< double > & val)
Definition at line 50 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetGradientDirections().
Referenced by SetMovingModels().
void anima::ApproximateMCMSmoothingCostFunction::SetBValueWeightIndexes (const std::vector< unsigned int > & val)
Definition at line 66 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetSphereWeights().
Referenced by SetGradientDirections().
void anima::ApproximateMCMSmoothingCostFunction::SetGradientDirections (const std::vector< GradientType > & val)
Definition at line 58 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetBValueWeightIndexes().
Referenced by SetBValues().
void anima::ApproximateMCMSmoothingCostFunction::SetMovingModels (const std::vector< MCMPointer > & movingModels, const std::vector< GradientType > & gradients, const std::vector< double > & bValues)
Definition at line 29 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetBValues().
Referenced by SetReferenceModels().
virtual void anima::ApproximateMCMSmoothingCostFunction::SetParameterScale (double _arg) virtual
void anima::ApproximateMCMSmoothingCostFunction::SetReferenceModels (const std::vector< MCMPointer > & refModels, const std::vector< GradientType > & gradients, const std::vector< double > & bValues)
Definition at line 8 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetMovingModels().
void anima::ApproximateMCMSmoothingCostFunction::SetSphereWeights (const std::vector< double > & val)
Definition at line 74 of file animaApproximateMCMSmoothingCostFunction.cxx.
References GetValue().
Referenced by SetBValueWeightIndexes().
The documentation for this class was generated from the following files:
animaApproximateMCMSmoothingCostFunction.h
animaApproximateMCMSmoothingCostFunction.cxx