ANIMA: anima::FreeWaterCompartment Class Reference
anima::FreeWaterCompartment Class Reference
#include <animaFreeWaterCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::SmartPointer< Self > Pointer
typedef FreeWaterCompartment Self
typedef BaseIsotropicCompartment Superclass
Public Types inherited from anima::BaseIsotropicCompartment
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseIsotropicCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
virtual const char * GetNameOfClass () const
virtual ListType GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType GetParameterUpperBounds () ITK_OVERRIDE
Public Member Functions inherited from anima::BaseIsotropicCompartment
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
bool GetEstimateAxialDiffusivity ()
virtual double GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType GetParametersAsVector () ITK_OVERRIDE
virtual ListType GetSignalAttenuationJacobian (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform) ITK_OVERRIDE
Reimplements re-orientation, useless in isotropic water compartment.
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
std::vector< double > & GetBoundedSignVector ()
double GetBoundedSignVectorValue (unsigned int i)
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double bValue, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
bool GetUseBoundedOptimization ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-6)
Tests equality to another compartment up to a constant.
virtual void SetAxialDiffusivity (double num)
void SetBoundedSignVectorValue (unsigned int i, double val)
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
void SetUseBoundedOptimization (bool x)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual ListType BoundParameters (const ListType &params) ITK_OVERRIDE
FreeWaterCompartment ()
double GetAxialDiffusivityDerivativeFactor () ITK_OVERRIDE
virtual void UnboundParameters (ListType &params) ITK_OVERRIDE
virtual ~FreeWaterCompartment ()
Protected Member Functions inherited from anima::BaseIsotropicCompartment
BaseIsotropicCompartment ()
virtual ~BaseIsotropicCompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
Static Protected Attributes inherited from anima::BaseCompartment
static const double m_AzimuthAngleUpperBound = 2.0 * M_PI
static const double m_DefaultConcentrationUpperBound = 20
static const double m_DiffusivityLowerBound = 1e-5
static const double m_DiffusivityUpperBound = 3e-3
static const double m_Epsilon = 1.0e-2
static const double m_PolarAngleUpperBound = M_PI
static const double m_RadialDiffusivityUpperBound = 1e-3
static const unsigned int m_SpaceDimension = 3
static const double m_ZeroLowerBound = 0.0
Detailed Description
Definition at line 9 of file animaFreeWaterCompartment.h.
Member Typedef Documentation
typedef Superclass::Pointer anima::FreeWaterCompartment::BasePointer
Definition at line 15 of file animaFreeWaterCompartment.h.
typedef itk::SmartPointer<const Self> anima::FreeWaterCompartment::ConstPointer
Definition at line 17 of file animaFreeWaterCompartment.h.
typedef itk::SmartPointer<Self> anima::FreeWaterCompartment::Pointer
Definition at line 16 of file animaFreeWaterCompartment.h.
typedef FreeWaterCompartment anima::FreeWaterCompartment::Self
Definition at line 13 of file animaFreeWaterCompartment.h.
typedef BaseIsotropicCompartment anima::FreeWaterCompartment::Superclass
Definition at line 14 of file animaFreeWaterCompartment.h.
Constructor & Destructor Documentation
anima::FreeWaterCompartment::FreeWaterCompartment () inline protected
Definition at line 31 of file animaFreeWaterCompartment.h.
virtual anima::FreeWaterCompartment::~FreeWaterCompartment () inline protected virtual
Definition at line 36 of file animaFreeWaterCompartment.h.
Member Function Documentation
FreeWaterCompartment::ListType anima::FreeWaterCompartment::BoundParameters (const ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 36 of file animaFreeWaterCompartment.cxx.
References anima::mcm_utilities::ComputeBoundedValue(), anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::BaseCompartment::SetBoundedSignVectorValue().
virtual::itk::LightObject::Pointer anima::FreeWaterCompartment::CreateAnother (void) const
double anima::FreeWaterCompartment::GetAxialDiffusivityDerivativeFactor () protected virtual
Reimplemented from anima::BaseIsotropicCompartment.
Definition at line 50 of file animaFreeWaterCompartment.cxx.
References anima::mcm_utilities::BoundedDerivativeAddOn(), anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::GetBoundedSignVectorValue().
DiffusionModelCompartmentType anima::FreeWaterCompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 25 of file animaFreeWaterCompartment.h.
References anima::FreeWater.
virtual const char* anima::FreeWaterCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseIsotropicCompartment.
FreeWaterCompartment::ListType anima::FreeWaterCompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 9 of file animaFreeWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::BaseIsotropicCompartment::GetNumberOfParameters().
FreeWaterCompartment::ListType anima::FreeWaterCompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 19 of file animaFreeWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::BaseIsotropicCompartment::GetNumberOfParameters().
static Pointer anima::FreeWaterCompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
void anima::FreeWaterCompartment::UnboundParameters (ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 29 of file animaFreeWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::mcm_utilities::UnboundValue().
The documentation for this class was generated from the following files:
animaFreeWaterCompartment.h
animaFreeWaterCompartment.cxx