ANIMA: anima::BlockMatchingInitializer< PixelType, NDimensions > Class Template Reference
anima::BlockMatchingInitializer< PixelType, NDimensions > Class Template Reference
#include <animaBlockMatchInitializer.h>
Classes
struct BlockGeneratorThreadStruct
struct pair_comparator
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef ScalarImageType::RegionType ImageRegionType
typedef ScalarImageType::IndexType IndexType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, NDimensions > MaskImageType
typedef itk::SmartPointer< Self > Pointer
typedef ScalarImageType::PointType PointType
typedef ScalarImageType::Pointer ScalarImagePointer
typedef itk::Image< PixelType, NDimensions > ScalarImageType
typedef BlockMatchingInitializer< PixelType, NDimensions > Self
typedef itk::Object Superclass
typedef VectorImageType::Pointer VectorImagePointer
typedef itk::VectorImage< PixelType, NDimensions > VectorImageType
typedef WeightImageType::Pointer WeightImagePointer
typedef itk::Image< double, NDimensions > WeightImageType
Public Member Functions
void AddGenerationMask (MaskImageType *mask)
virtual void AddReferenceImage (itk::ImageBase< NDimensions > *refImage)
void clearGenerationMasks ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
WeightImagePointer & GetBlockDamWeights ()
virtual unsigned int GetBlockSize ()
virtual unsigned int GetBlockSpacing ()
virtual bool GetComputeOuterDam ()
virtual double GetDamDistance ()
itk::ImageBase< NDimensions > * GetFirstReferenceImage ()
std::vector< unsigned int > & GetMaskStartingIndexes ()
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfThreads ()
virtual double GetOrientedModelVarianceThreshold ()
std::vector< ImageRegionType > & GetOutput ()
std::vector< PointType > & GetOutputPositions ()
virtual double GetPercentageKept ()
ScalarImageType * GetReferenceScalarImage (unsigned int i)
VectorImageType * GetReferenceVectorImage (unsigned int i)
virtual ImageRegionType GetRequestedRegion ()
virtual double GetScalarVarianceThreshold ()
void RegionBlockGenerator (BlockGeneratorThreadStruct *workStr, unsigned int threadId)
void SetBlockSize (unsigned int val)
void SetBlockSpacing (unsigned int val)
void SetComputeOuterDam (bool val)
void SetDamDistance (double val)
virtual void SetNumberOfThreads (unsigned int _arg)
void SetOrientedModelVarianceThreshold (double val)
void SetPercentageKept (double val)
void SetRequestedRegion (const ImageRegionType &val)
void SetScalarVarianceThreshold (double val)
void Update ()
Static Public Member Functions
static Pointer New ()
static ITK_THREAD_RETURN_TYPE ThreadBlockGenerator (void *arg)
Protected Member Functions
BlockMatchingInitializer ()
bool CheckBlockConditions (ImageRegionType &region, double &blockVariance, BlockGeneratorThreadStruct *workStr, unsigned int threadId)
virtual bool CheckOrientedModelVariance (unsigned int imageIndex, ImageRegionType &region, double &blockVariance, BlockGeneratorThreadStruct *workStr, unsigned int threadId)
bool CheckScalarVariance (ScalarImageType *refImage, ImageRegionType &region, double &blockVariance)
void ComputeBlocksOnGenerationMask (unsigned int maskIndex)
void ComputeOuterDamFromBlocks ()
virtual void InitializeThreading (unsigned int maskIndex, BlockGeneratorThreadStruct *&workStr)
bool ProgressCounter (std::vector< unsigned int > &counter, std::vector< unsigned int > &bounds)
virtual ~BlockMatchingInitializer ()
Detailed Description
template<class PixelType, unsigned int NDimensions = 3>
class anima::BlockMatchingInitializer< PixelType, NDimensions >
Definition at line 14 of file animaBlockMatchInitializer.h.
Member Typedef Documentation
template<class PixelType, unsigned int NDimensions = 3> typedef itk::SmartPointer<const Self> anima::BlockMatchingInitializer< PixelType, NDimensions >::ConstPointer
Definition at line 21 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef ScalarImageType::RegionType anima::BlockMatchingInitializer< PixelType, NDimensions >::ImageRegionType
Definition at line 37 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef ScalarImageType::IndexType anima::BlockMatchingInitializer< PixelType, NDimensions >::IndexType
Definition at line 26 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef MaskImageType::Pointer anima::BlockMatchingInitializer< PixelType, NDimensions >::MaskImagePointer
Definition at line 41 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef itk::Image<unsigned char, NDimensions> anima::BlockMatchingInitializer< PixelType, NDimensions >::MaskImageType
Definition at line 29 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef itk::SmartPointer<Self> anima::BlockMatchingInitializer< PixelType, NDimensions >::Pointer
Definition at line 20 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef ScalarImageType::PointType anima::BlockMatchingInitializer< PixelType, NDimensions >::PointType
Definition at line 27 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef ScalarImageType::Pointer anima::BlockMatchingInitializer< PixelType, NDimensions >::ScalarImagePointer
Definition at line 39 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef itk::Image<PixelType, NDimensions> anima::BlockMatchingInitializer< PixelType, NDimensions >::ScalarImageType
Definition at line 23 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef BlockMatchingInitializer<PixelType,NDimensions> anima::BlockMatchingInitializer< PixelType, NDimensions >::Self
Definition at line 19 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef itk::Object anima::BlockMatchingInitializer< PixelType, NDimensions >::Superclass
Definition at line 18 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef VectorImageType::Pointer anima::BlockMatchingInitializer< PixelType, NDimensions >::VectorImagePointer
Definition at line 40 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef itk::VectorImage<PixelType, NDimensions> anima::BlockMatchingInitializer< PixelType, NDimensions >::VectorImageType
Definition at line 28 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef WeightImageType::Pointer anima::BlockMatchingInitializer< PixelType, NDimensions >::WeightImagePointer
Definition at line 25 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> typedef itk::Image<double, NDimensions> anima::BlockMatchingInitializer< PixelType, NDimensions >::WeightImageType
Definition at line 24 of file animaBlockMatchInitializer.h.
Constructor & Destructor Documentation
template<class PixelType, unsigned int NDimensions = 3> anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockMatchingInitializer () inline protected
Definition at line 108 of file animaBlockMatchInitializer.h.
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::pair_comparator::operator()().
template<class PixelType, unsigned int NDimensions = 3> virtual anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer () inline protected virtual
Definition at line 126 of file animaBlockMatchInitializer.h.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckBlockConditions(), anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckOrientedModelVariance(), anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckScalarVariance(), anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeBlocksOnGenerationMask(), anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeOuterDamFromBlocks(), anima::BlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading(), anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::maskIndex, and anima::BlockMatchingInitializer< PixelType, NDimensions >::ProgressCounter().
Member Function Documentation
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::AddGenerationMask (MaskImageType * mask)
Definition at line 77 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::GetFirstReferenceImage().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::AddReferenceImage(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::clearGenerationMasks().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::AddReferenceImage (itk::ImageBase< NDimensions > * refImage) virtual
Reimplemented in anima::MCMBlockMatchingInitializer< PixelType, NDimensions >.
Definition at line 58 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::AddGenerationMask().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::clearGenerationMasks(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::GetMaskStartingIndexes().
template<class PixelType , unsigned int NDimensions> bool anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckBlockConditions (ImageRegionType & region, double & blockVariance, BlockGeneratorThreadStruct * workStr, unsigned int threadId) protected
Definition at line 561 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckOrientedModelVariance().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::ProgressCounter(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer().
template<class PixelType , unsigned int NDimensions> bool anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckOrientedModelVariance (unsigned int imageIndex, ImageRegionType & region, double & blockVariance, BlockGeneratorThreadStruct * workStr, unsigned int threadId) protected virtual
Reimplemented in anima::MCMBlockMatchingInitializer< PixelType, NDimensions >.
Definition at line 602 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckScalarVariance().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckBlockConditions(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer().
template<class PixelType , unsigned int NDimensions> bool anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckScalarVariance (ScalarImageType * refImage, ImageRegionType & region, double & blockVariance) protected
Definition at line 656 of file animaBlockMatchInitializer.hxx.
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckOrientedModelVariance(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer().
template<class PixelType, unsigned int NDimensions = 3> void anima::BlockMatchingInitializer< PixelType, NDimensions >::clearGenerationMasks () inline
Definition at line 70 of file animaBlockMatchInitializer.h.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::AddGenerationMask(), anima::BlockMatchingInitializer< PixelType, NDimensions >::AddReferenceImage(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::GetFirstReferenceImage().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeBlocksOnGenerationMask (unsigned int maskIndex) protected
Definition at line 237 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blocks_positions, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blocks_variances, anima::BlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading(), anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::tmpOutput, and anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::totalNumberOfBlocks.
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::Update(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeOuterDamFromBlocks () protected
Definition at line 478 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::ProgressCounter().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::RegionBlockGenerator(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer().
template<class PixelType, unsigned int NDimensions = 3> virtual::itk::LightObject::Pointer anima::BlockMatchingInitializer< PixelType, NDimensions >::CreateAnother (void) const
template<class PixelType , unsigned int NDimensions> BlockMatchingInitializer< PixelType, NDimensions >::WeightImagePointer & anima::BlockMatchingInitializer< PixelType, NDimensions >::GetBlockDamWeights ()
Definition at line 38 of file animaBlockMatchInitializer.hxx.
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOutputPositions(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceVectorImage().
template<class PixelType, unsigned int NDimensions = 3> virtual unsigned int anima::BlockMatchingInitializer< PixelType, NDimensions >::GetBlockSize () virtual
template<class PixelType, unsigned int NDimensions = 3> virtual unsigned int anima::BlockMatchingInitializer< PixelType, NDimensions >::GetBlockSpacing () virtual
template<class PixelType, unsigned int NDimensions = 3> virtual bool anima::BlockMatchingInitializer< PixelType, NDimensions >::GetComputeOuterDam () virtual
template<class PixelType, unsigned int NDimensions = 3> virtual double anima::BlockMatchingInitializer< PixelType, NDimensions >::GetDamDistance () virtual
template<class PixelType , unsigned int NDimensions> itk::ImageBase< NDimensions > * anima::BlockMatchingInitializer< PixelType, NDimensions >::GetFirstReferenceImage ()
Definition at line 86 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetPercentageKept().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::AddGenerationMask(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::clearGenerationMasks().
template<class PixelType , unsigned int NDimensions> std::vector< unsigned int > & anima::BlockMatchingInitializer< PixelType, NDimensions >::GetMaskStartingIndexes ()
Definition at line 47 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::AddReferenceImage().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceVectorImage().
template<class PixelType, unsigned int NDimensions = 3> virtual const char* anima::BlockMatchingInitializer< PixelType, NDimensions >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented in anima::MCMBlockMatchingInitializer< PixelType, NDimensions >.
template<class PixelType, unsigned int NDimensions = 3> virtual unsigned int anima::BlockMatchingInitializer< PixelType, NDimensions >::GetNumberOfThreads () virtual
template<class PixelType, unsigned int NDimensions = 3> virtual double anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOrientedModelVarianceThreshold () virtual
template<class PixelType , unsigned int NDimensions> std::vector< typename BlockMatchingInitializer< PixelType, NDimensions >::ImageRegionType > & anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOutput ()
Definition at line 18 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOutputPositions().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceVectorImage().
template<class PixelType , unsigned int NDimensions> std::vector< typename BlockMatchingInitializer< PixelType, NDimensions >::PointType > & anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOutputPositions ()
Definition at line 28 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::GetBlockDamWeights().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOutput(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceVectorImage().
template<class PixelType, unsigned int NDimensions = 3> virtual double anima::BlockMatchingInitializer< PixelType, NDimensions >::GetPercentageKept () virtual
template<class PixelType, unsigned int NDimensions = 3> ScalarImageType* anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceScalarImage (unsigned int i) inline
Definition at line 76 of file animaBlockMatchInitializer.h.
template<class PixelType, unsigned int NDimensions = 3> VectorImageType* anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceVectorImage (unsigned int i) inline
Definition at line 77 of file animaBlockMatchInitializer.h.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::GetBlockDamWeights(), anima::BlockMatchingInitializer< PixelType, NDimensions >::GetMaskStartingIndexes(), anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOutput(), anima::BlockMatchingInitializer< PixelType, NDimensions >::GetOutputPositions(), anima::BlockMatchingInitializer< PixelType, NDimensions >::ThreadBlockGenerator(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::Update().
template<class PixelType, unsigned int NDimensions = 3> virtual ImageRegionType anima::BlockMatchingInitializer< PixelType, NDimensions >::GetRequestedRegion () virtual
template<class PixelType, unsigned int NDimensions = 3> virtual double anima::BlockMatchingInitializer< PixelType, NDimensions >::GetScalarVarianceThreshold () virtual
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading (unsigned int maskIndex, BlockGeneratorThreadStruct *& workStr) protected virtual
Reimplemented in anima::MCMBlockMatchingInitializer< PixelType, NDimensions >.
Definition at line 296 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blocks_positions, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blocks_variances, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blockStartOffsets, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::Filter, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::maskIndex, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::nb_blocks, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::startBlocks, anima::BlockMatchingInitializer< PixelType, NDimensions >::ThreadBlockGenerator(), anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::tmpOutput, and anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::totalNumberOfBlocks.
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeBlocksOnGenerationMask(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer().
template<class PixelType, unsigned int NDimensions = 3> static Pointer anima::BlockMatchingInitializer< PixelType, NDimensions >::New () static
Method for creation through the object factory.
template<class PixelType , unsigned int NDimensions> bool anima::BlockMatchingInitializer< PixelType, NDimensions >::ProgressCounter (std::vector< unsigned int > & counter, std::vector< unsigned int > & bounds) protected
Definition at line 534 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::CheckBlockConditions().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeOuterDamFromBlocks(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::~BlockMatchingInitializer().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::RegionBlockGenerator (BlockGeneratorThreadStruct * workStr, unsigned int threadId)
Definition at line 415 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blocks_positions, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blocks_variances, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::blockStartOffsets, anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeOuterDamFromBlocks(), anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::maskIndex, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::nb_blocks, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::startBlocks, anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::tmpOutput, and anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::totalNumberOfBlocks.
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::ThreadBlockGenerator(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::~BlockGeneratorThreadStruct().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetBlockSize (unsigned int val)
Definition at line 154 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetComputeOuterDam().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::SetBlockSpacing().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetBlockSpacing (unsigned int val)
Definition at line 143 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetBlockSize().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::SetRequestedRegion().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetComputeOuterDam (bool val)
Definition at line 165 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetDamDistance().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::SetBlockSize().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetDamDistance (double val)
Definition at line 176 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::Update().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::SetComputeOuterDam().
template<class PixelType, unsigned int NDimensions = 3> virtual void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetNumberOfThreads (unsigned int _arg) virtual
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetOrientedModelVarianceThreshold (double val)
Definition at line 121 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetRequestedRegion().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::SetScalarVarianceThreshold().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetPercentageKept (double val)
Definition at line 99 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetScalarVarianceThreshold().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::GetFirstReferenceImage().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetRequestedRegion (const ImageRegionType & val)
Definition at line 132 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetBlockSpacing().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::SetOrientedModelVarianceThreshold().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::SetScalarVarianceThreshold (double val)
Definition at line 110 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::SetOrientedModelVarianceThreshold().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::SetPercentageKept().
template<class PixelType , unsigned int NDimensions> ITK_THREAD_RETURN_TYPE anima::BlockMatchingInitializer< PixelType, NDimensions >::ThreadBlockGenerator (void * arg) static
Definition at line 400 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct::Filter, and anima::BlockMatchingInitializer< PixelType, NDimensions >::RegionBlockGenerator().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceVectorImage(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading().
template<class PixelType , unsigned int NDimensions> void anima::BlockMatchingInitializer< PixelType, NDimensions >::Update ()
Definition at line 187 of file animaBlockMatchInitializer.hxx.
References anima::BlockMatchingInitializer< PixelType, NDimensions >::ComputeBlocksOnGenerationMask().
Referenced by anima::BlockMatchingInitializer< PixelType, NDimensions >::GetReferenceVectorImage(), and anima::BlockMatchingInitializer< PixelType, NDimensions >::SetDamDistance().
The documentation for this class was generated from the following files:
animaBlockMatchInitializer.h
animaBlockMatchInitializer.hxx