ANIMA: anima::StationaryWaterCompartment Class Reference
anima::StationaryWaterCompartment Class Reference
#include <animaStationaryWaterCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::SmartPointer< Self > Pointer
typedef StationaryWaterCompartment Self
typedef BaseIsotropicCompartment Superclass
Public Types inherited from anima::BaseIsotropicCompartment
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseIsotropicCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
virtual const char * GetNameOfClass () const
virtual ListType GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType GetParameterUpperBounds () ITK_OVERRIDE
Public Member Functions inherited from anima::BaseIsotropicCompartment
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
bool GetEstimateAxialDiffusivity ()
virtual double GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType GetParametersAsVector () ITK_OVERRIDE
virtual ListType GetSignalAttenuationJacobian (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform) ITK_OVERRIDE
Reimplements re-orientation, useless in isotropic water compartment.
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
std::vector< double > & GetBoundedSignVector ()
double GetBoundedSignVectorValue (unsigned int i)
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double bValue, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
bool GetUseBoundedOptimization ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-6)
Tests equality to another compartment up to a constant.
virtual void SetAxialDiffusivity (double num)
void SetBoundedSignVectorValue (unsigned int i, double val)
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
void SetUseBoundedOptimization (bool x)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual ListType BoundParameters (const ListType &params) ITK_OVERRIDE
StationaryWaterCompartment ()
virtual void UnboundParameters (ListType &params) ITK_OVERRIDE
virtual ~StationaryWaterCompartment ()
Protected Member Functions inherited from anima::BaseIsotropicCompartment
BaseIsotropicCompartment ()
virtual double GetAxialDiffusivityDerivativeFactor ()
virtual ~BaseIsotropicCompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
Static Protected Attributes inherited from anima::BaseCompartment
static const double m_AzimuthAngleUpperBound = 2.0 * M_PI
static const double m_DefaultConcentrationUpperBound = 20
static const double m_DiffusivityLowerBound = 1e-5
static const double m_DiffusivityUpperBound = 3e-3
static const double m_Epsilon = 1.0e-2
static const double m_PolarAngleUpperBound = M_PI
static const double m_RadialDiffusivityUpperBound = 1e-3
static const unsigned int m_SpaceDimension = 3
static const double m_ZeroLowerBound = 0.0
Detailed Description
Definition at line 9 of file animaStationaryWaterCompartment.h.
Member Typedef Documentation
typedef Superclass::Pointer anima::StationaryWaterCompartment::BasePointer
Definition at line 15 of file animaStationaryWaterCompartment.h.
typedef itk::SmartPointer<const Self> anima::StationaryWaterCompartment::ConstPointer
Definition at line 17 of file animaStationaryWaterCompartment.h.
typedef itk::SmartPointer<Self> anima::StationaryWaterCompartment::Pointer
Definition at line 16 of file animaStationaryWaterCompartment.h.
typedef StationaryWaterCompartment anima::StationaryWaterCompartment::Self
Definition at line 13 of file animaStationaryWaterCompartment.h.
typedef BaseIsotropicCompartment anima::StationaryWaterCompartment::Superclass
Definition at line 14 of file animaStationaryWaterCompartment.h.
Constructor & Destructor Documentation
anima::StationaryWaterCompartment::StationaryWaterCompartment () inline protected
Definition at line 31 of file animaStationaryWaterCompartment.h.
virtual anima::StationaryWaterCompartment::~StationaryWaterCompartment () inline protected virtual
Definition at line 37 of file animaStationaryWaterCompartment.h.
Member Function Documentation
StationaryWaterCompartment::ListType anima::StationaryWaterCompartment::BoundParameters (const ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 23 of file animaStationaryWaterCompartment.cxx.
virtual::itk::LightObject::Pointer anima::StationaryWaterCompartment::CreateAnother (void) const
DiffusionModelCompartmentType anima::StationaryWaterCompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 25 of file animaStationaryWaterCompartment.h.
References anima::StationaryWater.
virtual const char* anima::StationaryWaterCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseIsotropicCompartment.
StationaryWaterCompartment::ListType anima::StationaryWaterCompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 6 of file animaStationaryWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetNumberOfParameters().
StationaryWaterCompartment::ListType anima::StationaryWaterCompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 12 of file animaStationaryWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetNumberOfParameters().
static Pointer anima::StationaryWaterCompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
void anima::StationaryWaterCompartment::UnboundParameters (ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 18 of file animaStationaryWaterCompartment.cxx.
The documentation for this class was generated from the following files:
animaStationaryWaterCompartment.h
animaStationaryWaterCompartment.cxx