ANIMA: anima::BaseCompartment Class Reference
anima::BaseCompartment Class Reference abstract
#include <animaBaseCompartment.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
std::vector< double > & GetBoundedSignVector ()
double GetBoundedSignVectorValue (unsigned int i)
virtual unsigned int GetCompartmentSize ()=0
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
virtual DiffusionModelCompartmentType GetCompartmentType ()=0
Utility function to return compartment type without needing dynamic casts.
virtual ModelOutputVectorType & GetCompartmentVector ()=0
Get compartment overall description vector, mainly for writing, should be self-contained.
virtual const Matrix3DType & GetDiffusionTensor ()
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetExtraAxonalFraction ()
virtual double GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType &gradient)=0
virtual double GetFractionalAnisotropy ()
virtual double GetLogDiffusionProfile (const Vector3DType &sample)=0
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfParameters ()=0
Number of optimized parameters: smaller than total number of parameters.
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual ListType GetParameterLowerBounds ()=0
virtual ListType GetParametersAsVector ()=0
virtual ListType GetParameterUpperBounds ()=0
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double bValue, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
virtual ListType GetSignalAttenuationJacobian (double bValue, const Vector3DType &gradient)=0
bool GetUseBoundedOptimization ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-6)
Tests equality to another compartment up to a constant.
virtual void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform)
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
virtual void SetAxialDiffusivity (double num)
void SetBoundedSignVectorValue (unsigned int i, double val)
virtual void SetCompartmentVector (ModelOutputVectorType &compartmentVector)=0
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetParametersFromVector (const ListType &params)=0
Various methods for optimization parameters setting and getting.
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
void SetUseBoundedOptimization (bool x)
Protected Member Functions
BaseCompartment ()
virtual ListType BoundParameters (const ListType &params)=0
virtual void UnboundParameters (ListType &params)=0
virtual ~BaseCompartment ()
Protected Attributes
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
Static Protected Attributes
static const double m_AzimuthAngleUpperBound = 2.0 * M_PI
static const double m_DefaultConcentrationUpperBound = 20
static const double m_DiffusivityLowerBound = 1e-5
static const double m_DiffusivityUpperBound = 3e-3
static const double m_Epsilon = 1.0e-2
static const double m_PolarAngleUpperBound = M_PI
static const double m_RadialDiffusivityUpperBound = 1e-3
static const unsigned int m_SpaceDimension = 3
static const double m_ZeroLowerBound = 0.0
Detailed Description
Definition at line 38 of file animaBaseCompartment.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::BaseCompartment::ConstPointer
Definition at line 45 of file animaBaseCompartment.h.
typedef std::vector<double> anima::BaseCompartment::ListType
Definition at line 55 of file animaBaseCompartment.h.
typedef itk::Matrix<double, 3, 3> anima::BaseCompartment::Matrix3DType
Definition at line 46 of file animaBaseCompartment.h.
typedef itk::VariableLengthVector<double> anima::BaseCompartment::ModelOutputVectorType
Definition at line 56 of file animaBaseCompartment.h.
typedef itk::SmartPointer<Self> anima::BaseCompartment::Pointer
Definition at line 44 of file animaBaseCompartment.h.
typedef BaseCompartment anima::BaseCompartment::Self
Definition at line 42 of file animaBaseCompartment.h.
typedef itk::LightObject anima::BaseCompartment::Superclass
Definition at line 43 of file animaBaseCompartment.h.
typedef vnl_vector_fixed<double,3> anima::BaseCompartment::Vector3DType
Definition at line 54 of file animaBaseCompartment.h.
Constructor & Destructor Documentation
anima::BaseCompartment::BaseCompartment () inline protected
Definition at line 123 of file animaBaseCompartment.h.
virtual anima::BaseCompartment::~BaseCompartment () inline protected virtual
Definition at line 138 of file animaBaseCompartment.h.
Member Function Documentation
virtual ListType anima::BaseCompartment::BoundParameters (const ListType & params) protected pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, anima::StationaryWaterCompartment, anima::FreeWaterCompartment, and anima::IsotropicRestrictedWaterCompartment.
Referenced by anima::BaseIsotropicCompartment::SetParametersFromVector().
void anima::BaseCompartment::CopyFromOther (Self * rhs) virtual
Copy internal parameters from another compartment, faster than a set/get compartment vector.
Definition at line 104 of file animaBaseCompartment.cxx.
References GetAxialDiffusivity(), GetExtraAxonalFraction(), GetOrientationConcentration(), GetOrientationPhi(), GetOrientationTheta(), GetPerpendicularAngle(), GetRadialDiffusivity1(), and GetRadialDiffusivity2().
virtual double anima::BaseCompartment::GetAxialDiffusivity () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 96 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::TensorCompartment::GetAxialDiffusivity(), anima::FreeWaterCompartment::GetAxialDiffusivityDerivativeFactor(), anima::IsotropicRestrictedWaterCompartment::GetAxialDiffusivityDerivativeFactor(), anima::BaseIsotropicCompartment::GetCompartmentVector(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::BaseIsotropicCompartment::GetDiffusionTensor(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::BaseIsotropicCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetFractionalAnisotropy(), anima::ZeppelinCompartment::GetFractionalAnisotropy(), anima::BaseIsotropicCompartment::GetLogDiffusionProfile(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::BaseIsotropicCompartment::GetParametersAsVector(), anima::StickCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), and IsEqual().
std::vector<double>& anima::BaseCompartment::GetBoundedSignVector () inline
Definition at line 118 of file animaBaseCompartment.h.
Referenced by anima::BaseIsotropicCompartment::SetParametersFromVector(), anima::StickCompartment::SetParametersFromVector(), anima::TensorCompartment::SetParametersFromVector(), and anima::ZeppelinCompartment::SetParametersFromVector().
double anima::BaseCompartment::GetBoundedSignVectorValue (unsigned int i) inline
Definition at line 119 of file animaBaseCompartment.h.
Referenced by anima::FreeWaterCompartment::GetAxialDiffusivityDerivativeFactor(), anima::IsotropicRestrictedWaterCompartment::GetAxialDiffusivityDerivativeFactor(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::TensorCompartment::GetSignalAttenuationJacobian(), and anima::ZeppelinCompartment::GetSignalAttenuationJacobian().
virtual unsigned int anima::BaseCompartment::GetCompartmentSize () pure virtual
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
virtual DiffusionModelCompartmentType anima::BaseCompartment::GetCompartmentType () pure virtual
Utility function to return compartment type without needing dynamic casts.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
Referenced by anima::MultiCompartmentModel::AddCompartment(), and IsEqual().
virtual ModelOutputVectorType& anima::BaseCompartment::GetCompartmentVector () pure virtual
Get compartment overall description vector, mainly for writing, should be self-contained.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
const BaseCompartment::Matrix3DType & anima::BaseCompartment::GetDiffusionTensor () virtual
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
Definition at line 137 of file animaBaseCompartment.cxx.
Referenced by IsEqual().
virtual double anima::BaseCompartment::GetExtraAxonalFraction () inline virtual
Definition at line 100 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), and IsEqual().
virtual double anima::BaseCompartment::GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType & gradient) pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
double anima::BaseCompartment::GetFractionalAnisotropy () virtual
Reimplemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
Definition at line 142 of file animaBaseCompartment.cxx.
virtual double anima::BaseCompartment::GetLogDiffusionProfile (const Vector3DType & sample) pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
virtual const char* anima::BaseCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, anima::StationaryWaterCompartment, and anima::BaseIsotropicCompartment.
virtual unsigned int anima::BaseCompartment::GetNumberOfParameters () pure virtual
Number of optimized parameters: smaller than total number of parameters.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
virtual double anima::BaseCompartment::GetOrientationConcentration () inline virtual
Definition at line 99 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), and IsEqual().
virtual double anima::BaseCompartment::GetOrientationPhi () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 94 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::TensorCompartment::GetOrientationPhi(), anima::StickCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeStickModelFromDTI(), and IsEqual().
virtual double anima::BaseCompartment::GetOrientationTheta () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 93 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::TensorCompartment::GetOrientationTheta(), anima::StickCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeStickModelFromDTI(), and IsEqual().
virtual ListType anima::BaseCompartment::GetParameterLowerBounds () pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
virtual ListType anima::BaseCompartment::GetParametersAsVector () pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
virtual ListType anima::BaseCompartment::GetParameterUpperBounds () pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
virtual double anima::BaseCompartment::GetPerpendicularAngle () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 95 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::TensorCompartment::GetPerpendicularAngle(), and IsEqual().
double anima::BaseCompartment::GetPredictedSignal (double bValue, const Vector3DType & gradient)
Definition at line 55 of file animaBaseCompartment.cxx.
virtual double anima::BaseCompartment::GetRadialDiffusivity1 () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 97 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetFractionalAnisotropy(), anima::ZeppelinCompartment::GetFractionalAnisotropy(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::StickCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::TensorCompartment::GetRadialDiffusivity1(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), IsEqual(), and anima::StickCompartment::SetParametersFromVector().
virtual double anima::BaseCompartment::GetRadialDiffusivity2 () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 98 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::TensorCompartment::GetRadialDiffusivity2(), and IsEqual().
virtual ListType anima::BaseCompartment::GetSignalAttenuationJacobian (double bValue, const Vector3DType & gradient) pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
bool anima::BaseCompartment::GetUseBoundedOptimization () inline
Definition at line 91 of file animaBaseCompartment.h.
Referenced by anima::BaseIsotropicCompartment::GetParametersAsVector(), anima::StickCompartment::GetParametersAsVector(), anima::TensorCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::BaseIsotropicCompartment::GetSignalAttenuationJacobian(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::BaseIsotropicCompartment::SetParametersFromVector(), anima::StickCompartment::SetParametersFromVector(), anima::ZeppelinCompartment::SetParametersFromVector(), and anima::TensorCompartment::SetParametersFromVector().
bool anima::BaseCompartment::IsEqual (Self * rhs, double tolerance = 1.0e-6) virtual
Tests equality to another compartment up to a constant.
Definition at line 62 of file animaBaseCompartment.cxx.
References anima::ComputeScalarProduct(), anima::DDI, GetAxialDiffusivity(), GetCompartmentType(), GetDiffusionTensor(), GetExtraAxonalFraction(), GetOrientationConcentration(), GetOrientationPhi(), GetOrientationTheta(), GetPerpendicularAngle(), GetRadialDiffusivity1(), GetRadialDiffusivity2(), and anima::TransformSphericalToCartesianCoordinates().
void anima::BaseCompartment::Reorient (vnl_matrix< double > & orientationMatrix, bool affineTransform) virtual
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
Reimplemented in anima::TensorCompartment, and anima::BaseIsotropicCompartment.
Definition at line 116 of file animaBaseCompartment.cxx.
References anima::TransformCartesianToSphericalCoordinates(), and anima::TransformSphericalToCartesianCoordinates().
virtual void anima::BaseCompartment::SetAxialDiffusivity (double num) inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 106 of file animaBaseCompartment.h.
Referenced by anima::TensorCompartment::SetAxialDiffusivity(), anima::BaseIsotropicCompartment::SetCompartmentVector(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::BaseIsotropicCompartment::SetParametersFromVector(), anima::StickCompartment::SetParametersFromVector(), and anima::ZeppelinCompartment::SetParametersFromVector().
void anima::BaseCompartment::SetBoundedSignVectorValue (unsigned int i, double val) inline
Definition at line 120 of file animaBaseCompartment.h.
Referenced by anima::FreeWaterCompartment::BoundParameters(), anima::IsotropicRestrictedWaterCompartment::BoundParameters(), anima::StickCompartment::BoundParameters(), anima::ZeppelinCompartment::BoundParameters(), and anima::TensorCompartment::BoundParameters().
virtual void anima::BaseCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) pure virtual
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
Referenced by anima::MCMWeightedAverager::ComputeOutputTensorModel().
virtual void anima::BaseCompartment::SetExtraAxonalFraction (double num) inline virtual
Definition at line 110 of file animaBaseCompartment.h.
virtual void anima::BaseCompartment::SetOrientationConcentration (double num) inline virtual
Definition at line 109 of file animaBaseCompartment.h.
virtual void anima::BaseCompartment::SetOrientationPhi (double num) inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 104 of file animaBaseCompartment.h.
Referenced by anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::TensorCompartment::SetOrientationPhi(), anima::StickCompartment::SetParametersFromVector(), and anima::ZeppelinCompartment::SetParametersFromVector().
virtual void anima::BaseCompartment::SetOrientationTheta (double num) inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 103 of file animaBaseCompartment.h.
Referenced by anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::TensorCompartment::SetOrientationTheta(), anima::StickCompartment::SetParametersFromVector(), and anima::ZeppelinCompartment::SetParametersFromVector().
virtual void anima::BaseCompartment::SetParametersFromVector (const ListType & params) pure virtual
Various methods for optimization parameters setting and getting.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
virtual void anima::BaseCompartment::SetPerpendicularAngle (double num) inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 105 of file animaBaseCompartment.h.
Referenced by anima::TensorCompartment::SetPerpendicularAngle().
virtual void anima::BaseCompartment::SetRadialDiffusivity1 (double num) inline virtual
Reimplemented in anima::TensorCompartment, and anima::ZeppelinCompartment.
Definition at line 107 of file animaBaseCompartment.h.
Referenced by anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetRadialDiffusivity1(), and anima::TensorCompartment::SetRadialDiffusivity1().
virtual void anima::BaseCompartment::SetRadialDiffusivity2 (double num) inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 108 of file animaBaseCompartment.h.
Referenced by anima::ZeppelinCompartment::SetRadialDiffusivity1(), and anima::TensorCompartment::SetRadialDiffusivity2().
void anima::BaseCompartment::SetUseBoundedOptimization (bool x) inline
Definition at line 90 of file animaBaseCompartment.h.
virtual void anima::BaseCompartment::UnboundParameters (ListType & params) protected pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::StickCompartment, anima::StationaryWaterCompartment, anima::FreeWaterCompartment, and anima::IsotropicRestrictedWaterCompartment.
Referenced by anima::BaseIsotropicCompartment::GetParametersAsVector().
Member Data Documentation
const double anima::BaseCompartment::m_AzimuthAngleUpperBound = 2.0 * M_PI static protected
Definition at line 149 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn(), anima::StickCompartment::BoundParameters(), anima::ZeppelinCompartment::BoundParameters(), anima::TensorCompartment::BoundParameters(), anima::StickCompartment::GetParameterUpperBounds(), anima::ZeppelinCompartment::GetParameterUpperBounds(), anima::TensorCompartment::GetParameterUpperBounds(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::StickCompartment::UnboundParameters(), anima::ZeppelinCompartment::UnboundParameters(), and anima::TensorCompartment::UnboundParameters().
ModelOutputVectorType anima::BaseCompartment::m_CompartmentVector protected
Vector to hold working value of compartment vector.
Definition at line 158 of file animaBaseCompartment.h.
Referenced by anima::BaseIsotropicCompartment::GetCompartmentVector(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), and anima::TensorCompartment::GetCompartmentVector().
const double anima::BaseCompartment::m_DefaultConcentrationUpperBound = 20 static protected
Definition at line 152 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn().
Matrix3DType anima::BaseCompartment::m_DiffusionTensor protected
Matrix to hold working value of diffusion tensor approximation to the model.
Definition at line 155 of file animaBaseCompartment.h.
Referenced by anima::StickCompartment::GetDiffusionTensor(), and anima::ZeppelinCompartment::GetDiffusionTensor().
const double anima::BaseCompartment::m_DiffusivityLowerBound = 1e-5 static protected
Definition at line 147 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn(), anima::ZeppelinCompartment::BoundParameters(), anima::TensorCompartment::BoundParameters(), anima::ZeppelinCompartment::GetParameterLowerBounds(), anima::TensorCompartment::GetParameterLowerBounds(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::UnboundParameters(), anima::TensorCompartment::UnboundParameters(), and anima::TensorCompartment::UpdateParametersFromTensor().
const double anima::BaseCompartment::m_DiffusivityUpperBound = 3e-3 static protected
Definition at line 150 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn(), anima::StickCompartment::BoundParameters(), anima::ZeppelinCompartment::BoundParameters(), anima::TensorCompartment::BoundParameters(), anima::StickCompartment::GetParameterUpperBounds(), anima::ZeppelinCompartment::GetParameterUpperBounds(), anima::TensorCompartment::GetParameterUpperBounds(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::StickCompartment::UnboundParameters(), anima::ZeppelinCompartment::UnboundParameters(), anima::TensorCompartment::UnboundParameters(), and anima::TensorCompartment::UpdateParametersFromTensor().
const double anima::BaseCompartment::m_Epsilon = 1.0e-2 static protected
Definition at line 146 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn().
const double anima::BaseCompartment::m_PolarAngleUpperBound = M_PI static protected
Definition at line 148 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn(), anima::StickCompartment::BoundParameters(), anima::ZeppelinCompartment::BoundParameters(), anima::TensorCompartment::BoundParameters(), anima::StickCompartment::GetParameterUpperBounds(), anima::ZeppelinCompartment::GetParameterUpperBounds(), anima::TensorCompartment::GetParameterUpperBounds(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::StickCompartment::UnboundParameters(), anima::ZeppelinCompartment::UnboundParameters(), and anima::TensorCompartment::UnboundParameters().
const double anima::BaseCompartment::m_RadialDiffusivityUpperBound = 1e-3 static protected
Definition at line 151 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn(), anima::ZeppelinCompartment::BoundParameters(), anima::TensorCompartment::BoundParameters(), anima::ZeppelinCompartment::GetParameterUpperBounds(), anima::TensorCompartment::GetParameterUpperBounds(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::UnboundParameters(), and anima::TensorCompartment::UnboundParameters().
const unsigned int anima::BaseCompartment::m_SpaceDimension = 3 static protected
Definition at line 143 of file animaBaseCompartment.h.
Referenced by anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::BaseIsotropicCompartment::GetDiffusionTensor(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::TensorCompartment::GetFourierTransformedDiffusionProfile(), anima::TensorCompartment::GetLogDiffusionProfile(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::TensorCompartment::SetCompartmentVector(), anima::TensorCompartment::UpdateDiffusionTensor(), and anima::TensorCompartment::UpdateParametersFromTensor().
const double anima::BaseCompartment::m_ZeroLowerBound = 0.0 static protected
Definition at line 145 of file animaBaseCompartment.h.
Referenced by anima::mcm_utilities::BoundedDerivativeAddOn(), anima::StickCompartment::BoundParameters(), anima::ZeppelinCompartment::BoundParameters(), anima::TensorCompartment::BoundParameters(), anima::StickCompartment::GetParameterLowerBounds(), anima::ZeppelinCompartment::GetParameterLowerBounds(), anima::TensorCompartment::GetParameterLowerBounds(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::StickCompartment::UnboundParameters(), anima::ZeppelinCompartment::UnboundParameters(), and anima::TensorCompartment::UnboundParameters().
The documentation for this class was generated from the following files:
animaBaseCompartment.h
animaBaseCompartment.cxx