ANIMA: anima::StickCompartment Class Reference
anima::StickCompartment Class Reference
#include <animaStickCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef StickCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType GetParametersAsVector () ITK_OVERRIDE
virtual ListType GetParameterUpperBounds () ITK_OVERRIDE
virtual ListType GetSignalAttenuationJacobian (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
std::vector< double > & GetBoundedSignVector ()
double GetBoundedSignVectorValue (unsigned int i)
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double bValue, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
bool GetUseBoundedOptimization ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-6)
Tests equality to another compartment up to a constant.
virtual void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform)
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
virtual void SetAxialDiffusivity (double num)
void SetBoundedSignVectorValue (unsigned int i, double val)
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
void SetUseBoundedOptimization (bool x)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual ListType BoundParameters (const ListType &params) ITK_OVERRIDE
StickCompartment ()
virtual void UnboundParameters (ListType &params) ITK_OVERRIDE
virtual ~StickCompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
Static Protected Attributes inherited from anima::BaseCompartment
static const double m_AzimuthAngleUpperBound = 2.0 * M_PI
static const double m_DefaultConcentrationUpperBound = 20
static const double m_DiffusivityLowerBound = 1e-5
static const double m_DiffusivityUpperBound = 3e-3
static const double m_Epsilon = 1.0e-2
static const double m_PolarAngleUpperBound = M_PI
static const double m_RadialDiffusivityUpperBound = 1e-3
static const unsigned int m_SpaceDimension = 3
static const double m_ZeroLowerBound = 0.0
Detailed Description
Definition at line 9 of file animaStickCompartment.h.
Member Typedef Documentation
typedef Superclass::Pointer anima::StickCompartment::BasePointer
Definition at line 15 of file animaStickCompartment.h.
typedef itk::SmartPointer<const Self> anima::StickCompartment::ConstPointer
Definition at line 17 of file animaStickCompartment.h.
typedef Superclass::Matrix3DType anima::StickCompartment::Matrix3DType
Definition at line 20 of file animaStickCompartment.h.
typedef Superclass::ModelOutputVectorType anima::StickCompartment::ModelOutputVectorType
Definition at line 18 of file animaStickCompartment.h.
typedef itk::SmartPointer<Self> anima::StickCompartment::Pointer
Definition at line 16 of file animaStickCompartment.h.
typedef StickCompartment anima::StickCompartment::Self
Definition at line 13 of file animaStickCompartment.h.
typedef BaseCompartment anima::StickCompartment::Superclass
Definition at line 14 of file animaStickCompartment.h.
typedef Superclass::Vector3DType anima::StickCompartment::Vector3DType
Definition at line 19 of file animaStickCompartment.h.
Constructor & Destructor Documentation
anima::StickCompartment::StickCompartment () inline protected
Definition at line 52 of file animaStickCompartment.h.
virtual anima::StickCompartment::~StickCompartment () inline protected virtual
Definition at line 59 of file animaStickCompartment.h.
Member Function Documentation
StickCompartment::ListType anima::StickCompartment::BoundParameters (const ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 134 of file animaStickCompartment.cxx.
References anima::mcm_utilities::ComputeBoundedValue(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_ZeroLowerBound, and anima::BaseCompartment::SetBoundedSignVectorValue().
Referenced by SetParametersFromVector().
virtual::itk::LightObject::Pointer anima::StickCompartment::CreateAnother (void) const
unsigned int anima::StickCompartment::GetCompartmentSize () virtual
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implements anima::BaseCompartment.
Definition at line 209 of file animaStickCompartment.cxx.
Referenced by GetCompartmentVector(), GetNumberOfParameters(), and SetCompartmentVector().
DiffusionModelCompartmentType anima::StickCompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 28 of file animaStickCompartment.h.
References anima::Stick.
StickCompartment::ModelOutputVectorType & anima::StickCompartment::GetCompartmentVector () virtual
Get compartment overall description vector, mainly for writing, should be self-contained.
Implements anima::BaseCompartment.
Definition at line 229 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetCompartmentSize(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::m_CompartmentVector, anima::BaseCompartment::m_SpaceDimension, and anima::TransformSphericalToCartesianCoordinates().
const StickCompartment::Matrix3DType & anima::StickCompartment::GetDiffusionTensor () virtual
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented from anima::BaseCompartment.
Definition at line 254 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::m_DiffusionTensor, anima::BaseCompartment::m_SpaceDimension, and anima::TransformSphericalToCartesianCoordinates().
double anima::StickCompartment::GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 9 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), and anima::BaseCompartment::GetRadialDiffusivity1().
Referenced by GetSignalAttenuationJacobian().
double anima::StickCompartment::GetFractionalAnisotropy () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 275 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::GetRadialDiffusivity1().
double anima::StickCompartment::GetLogDiffusionProfile (const Vector3DType & sample) virtual
Implements anima::BaseCompartment.
Definition at line 61 of file animaStickCompartment.cxx.
References anima::ComputeScalarProduct(), anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), and anima::TransformSphericalToCartesianCoordinates().
virtual const char* anima::StickCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseCompartment.
unsigned int anima::StickCompartment::GetNumberOfParameters () virtual
Number of optimized parameters: smaller than total number of parameters.
Implements anima::BaseCompartment.
Definition at line 214 of file animaStickCompartment.cxx.
References GetCompartmentSize().
Referenced by GetParameterLowerBounds(), GetParametersAsVector(), GetParameterUpperBounds(), GetSignalAttenuationJacobian(), and SetParametersFromVector().
StickCompartment::ListType anima::StickCompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 115 of file animaStickCompartment.cxx.
References GetNumberOfParameters(), and anima::BaseCompartment::m_ZeroLowerBound.
StickCompartment::ListType anima::StickCompartment::GetParametersAsVector () virtual
Implements anima::BaseCompartment.
Definition at line 99 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::GetUseBoundedOptimization(), and UnboundParameters().
StickCompartment::ListType anima::StickCompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 121 of file animaStickCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityUpperBound, and anima::BaseCompartment::m_PolarAngleUpperBound.
StickCompartment::ListType anima::StickCompartment::GetSignalAttenuationJacobian (double bValue, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 19 of file animaStickCompartment.cxx.
References anima::mcm_utilities::BoundedDerivativeAddOn(), anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetBoundedSignVectorValue(), GetFourierTransformedDiffusionProfile(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::GetUseBoundedOptimization(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, and anima::BaseCompartment::m_ZeroLowerBound.
static Pointer anima::StickCompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
void anima::StickCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) virtual
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implements anima::BaseCompartment.
Definition at line 171 of file animaStickCompartment.cxx.
References GetCompartmentSize(), anima::BaseCompartment::m_SpaceDimension, anima::BaseCompartment::SetAxialDiffusivity(), anima::BaseCompartment::SetOrientationPhi(), anima::BaseCompartment::SetOrientationTheta(), anima::BaseCompartment::SetRadialDiffusivity1(), and anima::TransformCartesianToSphericalCoordinates().
void anima::StickCompartment::SetEstimateAxialDiffusivity (bool arg)
Definition at line 162 of file animaStickCompartment.cxx.
void anima::StickCompartment::SetParametersFromVector (const ListType & params) virtual
Various methods for optimization parameters setting and getting.
Implements anima::BaseCompartment.
Definition at line 75 of file animaStickCompartment.cxx.
References BoundParameters(), anima::BaseCompartment::GetBoundedSignVector(), GetNumberOfParameters(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::GetUseBoundedOptimization(), anima::BaseCompartment::SetAxialDiffusivity(), anima::BaseCompartment::SetOrientationPhi(), and anima::BaseCompartment::SetOrientationTheta().
void anima::StickCompartment::UnboundParameters (ListType & params) protected virtual
Implements anima::BaseCompartment.
Definition at line 153 of file animaStickCompartment.cxx.
References anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_ZeroLowerBound, and anima::mcm_utilities::UnboundValue().
Referenced by GetParametersAsVector().
The documentation for this class was generated from the following files:
animaStickCompartment.h
animaStickCompartment.cxx