ANIMA: anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType > Class Template Reference
anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType > Class Template Reference
#include <animaMCMEstimatorImageFilter.h>
Public Types
typedef anima::BaseCompartment BaseCompartmentType
typedef anima::MultiCompartmentModelCreator::CompartmentType CompartmentType
typedef itk::SmartPointer< const Self > ConstPointer
typedef CostFunctionBaseType::Pointer CostFunctionBasePointer
typedef itk::CostFunction CostFunctionBaseType
typedef vnl_vector_fixed< double, 3 > GradientType
typedef itk::Image< InputPixelType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
enum MaximumLikelihoodEstimationMode {
Marginal = 0,
Profile,
VariableProjection
}
typedef anima::MultiCompartmentModelCreator MCMCreatorType
typedef MCMCreatorType::MCMPointer MCMPointer
typedef MCMCreatorType::MCMType MCMType
typedef MCMType::ListType MCMVectorType
typedef anima::MCMImage< OutputPixelType, 3 > ModelImageType
typedef MoseImageType::Pointer MoseImagePointer
typedef itk::Image< unsigned char, 3 > MoseImageType
typedef OptimizerType::Pointer OptimizerPointer
typedef itk::NonLinearOptimizer OptimizerType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef OutputScalarImageType::Pointer OutputScalarImagePointer
typedef itk::Image< OutputPixelType, 3 > OutputScalarImageType
typedef OptimizerType::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef MCMEstimatorImageFilter< InputPixelType, OutputPixelType > Self
typedef anima::NDHaltonSequenceGenerator SequenceGeneratorType
enum SignalNoiseType {
Gaussian = 0,
NCC
}
Denotes noise type on input signal. Based on this, a different cost function should be created.
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::Image< InputPixelType, 3 > TInputImage
typedef anima::MCMImage< OutputPixelType, 3 > TOutputImage
typedef OutputImageType::PixelType VariableLengthVectorType
typedef VectorImageType::Pointer VectorImagePointer
typedef itk::VectorImage< OutputPixelType, 3 > VectorImageType
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, 3 > MaskImageType
typedef MaskImageType::RegionType MaskRegionType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > > Superclass
typedef itk::ImageSource< anima::MCMImage< OutputPixelType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
void AddGradientDirection (unsigned int i, GradientType &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
OutputScalarImageType * GetAICcVolume ()
OutputScalarImageType * GetB0Volume ()
std::vector< double > & GetBValuesList ()
std::vector< GradientType > & GetGradientDirections ()
MCMCreatorType * GetMCMCreator (unsigned int i)
virtual MaximumLikelihoodEstimationMode GetMLEstimationStrategy ()
MoseImageType * GetMoseVolume ()
virtual const char * GetNameOfClass () const
virtual MCMCreatorType * GetNewMCMCreatorInstance ()
virtual SignalNoiseType GetNoiseType ()
virtual unsigned int GetNumberOfCoils ()
std::string GetOptimizer ()
OutputScalarImageType * GetSigmaSquareVolume ()
virtual bool GetVNLDerivativeComputation ()
virtual void SetAbsoluteCostChange (double _arg)
virtual void SetAxialDiffusivityFixedValue (double _arg)
virtual void SetB0Threshold (double _arg)
void SetBValuesList (std::vector< double > &mb)
virtual void SetCompartmentType (CompartmentType _arg)
virtual void SetExternalDTIParameters (bool _arg)
virtual void SetFindOptimalNumberOfCompartments (bool _arg)
virtual void SetFreeWaterProportionFixedValue (double _arg)
virtual void SetGTolerance (double _arg)
virtual void SetMaxEval (double _arg)
virtual void SetMLEstimationStrategy (MaximumLikelihoodEstimationMode _arg)
virtual void SetModelWithFreeWaterComponent (bool _arg)
virtual void SetModelWithRestrictedWaterComponent (bool _arg)
virtual void SetModelWithStationaryWaterComponent (bool _arg)
void SetMoseVolume (MoseImageType *img)
virtual void SetNoiseType (SignalNoiseType _arg)
virtual void SetNumberOfCoils (unsigned int _arg)
virtual void SetNumberOfCompartments (unsigned int _arg)
virtual void SetNumberOfRandomRestarts (unsigned int _arg)
void SetOptimizer (std::string &opt)
virtual void SetRadialDiffusivity1FixedValue (double _arg)
virtual void SetRadialDiffusivity2FixedValue (double _arg)
virtual void SetRestrictedWaterProportionFixedValue (double _arg)
virtual void SetStationaryWaterProportionFixedValue (double _arg)
virtual void SetUseCommonDiffusivities (bool _arg)
virtual void SetUseConcentrationBoundsFromDTI (bool _arg)
virtual void SetUseConstrainedDiffusivity (bool _arg)
virtual void SetUseConstrainedFreeWaterDiffusivity (bool _arg)
virtual void SetUseConstrainedIRWDiffusivity (bool _arg)
virtual void SetUseFixedWeights (bool _arg)
virtual void SetVNLDerivativeComputation (bool _arg)
virtual void SetXTolerance (double _arg)
void WriteMCMOutput (std::string fileName)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
static Pointer New ()
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
double ComputeAICcValue (MCMPointer &mcmValue, double costValue)
Compute AICc value from a cost function value and model.
virtual CostFunctionBasePointer CreateCostFunction (std::vector< double > &observedSignals, MCMPointer &mcmModel)
Create a cost function following the noise type and estimation mode.
OptimizerPointer CreateOptimizer (CostFunctionBasePointer &cost, itk::Array< double > &lowerBounds, itk::Array< double > &upperBounds)
Create an optimizer following the optimizer type and estimation mode.
void EstimateFreeWaterModel (MCMPointer &mcmValue, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Specific method for N=0 compartments estimation (only free water)
void GenerateOutputInformation () ITK_OVERRIDE
double GetCostValue (CostFunctionBasePointer &cost, ParametersType &p)
Utility function to get a value from a cost function.
void GetProfiledInformation (CostFunctionBasePointer &cost, MCMPointer &mcm, double &b0Value, double &sigmaSqValue)
Utility function to get profiled data from the cost function into an MCM model.
virtual void InitializeModelFromSimplifiedOne (MCMPointer &simplifiedModel, MCMPointer &complexModel)
Performs initialization from simplified model with the same number of compartments.
virtual void InitializeStickModelFromDTI (MCMPointer &simplifiedModel, MCMPointer &complexModel, SequenceGeneratorType &generator)
Performs initialization from single DTI.
void InitialOrientationsEstimation (MCMPointer &mcmValue, unsigned int currentNumberOfCompartments, BaseCompartment::ModelOutputVectorType &initialDTI, std::vector< double > &observedSignals, SequenceGeneratorType &generator, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Doing estimation only of multiple orientations.
MCMEstimatorImageFilter ()
void OptimizeNonIsotropicCompartments (MCMPointer &mcmValue, unsigned int currentNumberOfCompartments, BaseCompartment::ModelOutputVectorType &initialDTI, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Doing estimation of non isotropic compartments (for a given number of anisotropic compartments)
double PerformSingleOptimization (ParametersType &p, CostFunctionBasePointer &cost, itk::Array< double > &lowerBounds, itk::Array< double > &upperBounds)
Performs an optimization of the supplied cost function and parameters using the specified optimizer(s). Returns the optimized parameters.
void SampleStickModelCompartmentsFromDTI (BaseCompartmentType *tensorCompartment, MCMPointer &complexModel, SequenceGeneratorType &generator)
Performs direction sampling initialization from simplified model (handles only DTI right now)
virtual void SpecificModelEstimation (MCMPointer &mcmValue, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Perform additional estimation after ball and zeppelin if needed.
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
void TrunkModelEstimation (MCMPointer &mcmValue, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Doing estimation, calling initialization procedure until ball and zeppelin, returns AICc value.
virtual ~MCMEstimatorImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (anima::MCMImage< OutputPixelType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (anima::MCMImage< OutputPixelType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class InputPixelType, class OutputPixelType>
class anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >
Definition at line 106 of file animaMCMEstimatorImageFilter.h.
Member Typedef Documentation
template<class InputPixelType, class OutputPixelType> typedef anima::BaseCompartment anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BaseCompartmentType
Definition at line 130 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef anima::MultiCompartmentModelCreator::CompartmentType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CompartmentType
Definition at line 129 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::SmartPointer<const Self> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ConstPointer
Definition at line 120 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef CostFunctionBaseType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CostFunctionBasePointer
Definition at line 139 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::CostFunction anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CostFunctionBaseType
Definition at line 138 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef vnl_vector_fixed<double,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GradientType
Definition at line 174 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::Image<InputPixelType,4> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Image4DType
Definition at line 114 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef InputImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InputImagePointer
Definition at line 165 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef Superclass::InputImageRegionType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InputImageRegionType
Definition at line 171 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef TInputImage anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InputImageType
Image typedef support
Definition at line 163 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef Superclass::MaskImageType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MaskImageType
Superclass typedefs.
Definition at line 170 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef anima::MultiCompartmentModelCreator anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMCreatorType
Definition at line 128 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef MCMCreatorType::MCMPointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMPointer
Definition at line 132 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef MCMCreatorType::MCMType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMType
Definition at line 131 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef MCMType::ListType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMVectorType
Definition at line 133 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef anima::MCMImage<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelImageType
Definition at line 113 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef MoseImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MoseImagePointer
Definition at line 123 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::Image<unsigned char,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MoseImageType
Definition at line 122 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef OptimizerType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizerPointer
Definition at line 136 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::NonLinearOptimizer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizerType
Definition at line 135 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef OutputImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputImagePointer
Definition at line 167 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef Superclass::OutputImageRegionType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputImageRegionType
Definition at line 172 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef TOutputImage anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputImageType
Definition at line 164 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef OutputScalarImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputScalarImagePointer
Definition at line 117 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::Image<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputScalarImageType
Definition at line 116 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef OptimizerType::ParametersType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ParametersType
Definition at line 137 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::SmartPointer<Self> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Pointer
Definition at line 119 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef MCMEstimatorImageFilter<InputPixelType, OutputPixelType> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Self
Standard class typedefs.
Definition at line 111 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef anima::NDHaltonSequenceGenerator anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SequenceGeneratorType
Definition at line 140 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Superclass
Definition at line 118 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::Image<InputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TInputImage
Definition at line 112 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef anima::MCMImage<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TOutputImage
Definition at line 115 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef OutputImageType::PixelType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::VariableLengthVectorType
Definition at line 166 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef VectorImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::VectorImagePointer
Definition at line 126 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> typedef itk::VectorImage<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::VectorImageType
Definition at line 125 of file animaMCMEstimatorImageFilter.h.
Member Enumeration Documentation
template<class InputPixelType, class OutputPixelType> enum anima::MCMEstimatorImageFilter::MaximumLikelihoodEstimationMode
Enumerator
Marginal
Profile
VariableProjection
Definition at line 149 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> enum anima::MCMEstimatorImageFilter::SignalNoiseType
Denotes noise type on input signal. Based on this, a different cost function should be created.
Enumerator
Gaussian
NCC
Definition at line 143 of file animaMCMEstimatorImageFilter.h.
Constructor & Destructor Documentation
template<class InputPixelType, class OutputPixelType> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMEstimatorImageFilter () inline protected
Definition at line 245 of file animaMCMEstimatorImageFilter.h.
References anima::Tensor.
template<class InputPixelType, class OutputPixelType> virtual anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter () inline protected virtual
Definition at line 298 of file animaMCMEstimatorImageFilter.h.
Member Function Documentation
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::AddGradientDirection (unsigned int i, GradientType & grad)
Definition at line 31 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNewMCMCreatorInstance().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >.
Definition at line 125 of file animaMCMEstimatorImageFilter.hxx.
References anima::GetTensorFromVectorRepresentation(), anima::ConcentrationUpperBoundSolverCostFunction::SetWMAxialDiffusivity(), anima::ConcentrationUpperBoundSolverCostFunction::SetWMRadialDiffusivity(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ThreadedGenerateData().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CheckComputationMask().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >.
Definition at line 96 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput().
template<class InputPixelType , class OutputPixelType > double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeAICcValue (MCMPointer & mcmValue, double costValue) protected
Compute AICc value from a cost function value and model.
Definition at line 1170 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeStickModelFromDTI().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
template<class InputPixelType, class OutputPixelType> virtual::itk::LightObject::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateAnother (void) const
template<class InputPixelType , class OutputPixelType > MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CostFunctionBasePointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction (std::vector< double > & observedSignals, MCMPointer & mcmModel) protected virtual
Create a cost function following the noise type and estimation mode.
Definition at line 635 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), anima::GaussianMCMVariableProjectionSingleValuedCostFunction::New(), anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::New(), anima::GaussianMCMCostFunction::New(), and anima::GaussianMCMVariableProjectionCost::New().
template<class InputPixelType , class OutputPixelType > MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizerPointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer (CostFunctionBasePointer & cost, itk::Array< double > & lowerBounds, itk::Array< double > & upperBounds) protected
Create an optimizer following the optimizer type and estimation mode.
Definition at line 970 of file animaMCMEstimatorImageFilter.hxx.
References anima::BaseMCMCostFunction::GetMCMStructure(), anima::NLOPTOptimizers::New(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::PerformSingleOptimization().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SpecificModelEstimation().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel (MCMPointer & mcmValue, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Specific method for N=0 compartments estimation (only free water)
Definition at line 570 of file animaMCMEstimatorImageFilter.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetFreeWaterProportionFixedValue(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MultiCompartmentModelCreator::SetRestrictedWaterProportionFixedValue(), anima::MultiCompartmentModelCreator::SetStationaryWaterProportionFixedValue(), anima::MultiCompartmentModelCreator::SetUseConstrainedFreeWaterDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedIRWDiffusivity(), and anima::MultiCompartmentModelCreator::SetUseFixedWeights().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation () protected
Definition at line 52 of file animaMCMEstimatorImageFilter.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MCMImage< TPixel, VImageDimension >::SetDescriptionModel(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNewMCMCreatorInstance().
template<class InputPixelType, class OutputPixelType> OutputScalarImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetAICcVolume () inline
Definition at line 226 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> OutputScalarImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetB0Volume () inline
Definition at line 227 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> std::vector<double>& anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetBValuesList () inline
Definition at line 219 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType , class OutputPixelType > double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue (CostFunctionBasePointer & cost, ParametersType & p) protected
Utility function to get a value from a cost function.
Definition at line 1110 of file animaMCMEstimatorImageFilter.hxx.
References anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetInternalCost(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation(), and anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetValue().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::PerformSingleOptimization().
template<class InputPixelType, class OutputPixelType> std::vector< GradientType >& anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetGradientDirections () inline
Definition at line 220 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> MCMCreatorType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMCMCreator (unsigned int i) inline
Definition at line 222 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> virtual MaximumLikelihoodEstimationMode anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMLEstimationStrategy () virtual
template<class InputPixelType, class OutputPixelType> MoseImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMoseVolume () inline
Definition at line 231 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> virtual const char* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >.
template<class InputPixelType , class OutputPixelType > MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMCreatorType * anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNewMCMCreatorInstance () virtual
Definition at line 44 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::AddGradientDirection().
template<class InputPixelType, class OutputPixelType> virtual SignalNoiseType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNoiseType () virtual
template<class InputPixelType, class OutputPixelType> virtual unsigned int anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNumberOfCoils () virtual
template<class InputPixelType, class OutputPixelType> std::string anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetOptimizer () inline
Definition at line 218 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation (CostFunctionBasePointer & cost, MCMPointer & mcm, double & b0Value, double & sigmaSqValue) protected
Utility function to get profiled data from the cost function into an MCM model.
Definition at line 1136 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeAICcValue(), anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetB0Value(), anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetB0Value(), anima::BaseMCMCostFunction::GetB0Value(), anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetOptimalWeights(), anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetOptimalWeights(), anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetSigmaSquare(), anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetSigmaSquare(), and anima::BaseMCMCostFunction::GetSigmaSquare().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue().
template<class InputPixelType, class OutputPixelType> OutputScalarImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetSigmaSquareVolume () inline
Definition at line 228 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> virtual bool anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetVNLDerivativeComputation () virtual
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeModelFromSimplifiedOne (MCMPointer & simplifiedModel, MCMPointer & complexModel) protected virtual
Performs initialization from simplified model with the same number of compartments.
Definition at line 1204 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SampleStickModelCompartmentsFromDTI().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeStickModelFromDTI().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeStickModelFromDTI (MCMPointer & simplifiedModel, MCMPointer & complexModel, SequenceGeneratorType & generator) protected virtual
Performs initialization from single DTI.
Definition at line 1186 of file animaMCMEstimatorImageFilter.hxx.
References anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeModelFromSimplifiedOne().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeAICcValue().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation (MCMPointer & mcmValue, unsigned int currentNumberOfCompartments, BaseCompartment::ModelOutputVectorType & initialDTI, std::vector< double > & observedSignals, SequenceGeneratorType & generator, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Doing estimation only of multiple orientations.
Definition at line 691 of file animaMCMEstimatorImageFilter.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MultiCompartmentModelCreator::SetFreeWaterProportionFixedValue(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MultiCompartmentModelCreator::SetRestrictedWaterProportionFixedValue(), anima::MultiCompartmentModelCreator::SetStationaryWaterProportionFixedValue(), anima::MultiCompartmentModelCreator::SetUseCommonDiffusivities(), anima::MultiCompartmentModelCreator::SetUseConstrainedDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedFreeWaterDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedIRWDiffusivity(), anima::MultiCompartmentModelCreator::SetUseFixedWeights(), anima::Stick, anima::Tensor, and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TrunkModelEstimation().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction().
template<class InputPixelType, class OutputPixelType> static Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::New () static
Method for creation through the object factory.
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments (MCMPointer & mcmValue, unsigned int currentNumberOfCompartments, BaseCompartment::ModelOutputVectorType & initialDTI, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Doing estimation of non isotropic compartments (for a given number of anisotropic compartments)
Definition at line 509 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::NDHaltonSequenceGenerator::SetLowerBounds(), anima::NDHaltonSequenceGenerator::SetUpperBounds(), anima::Stick, and anima::Zeppelin.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ThreadedGenerateData().
template<class InputPixelType , class OutputPixelType > double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::PerformSingleOptimization (ParametersType & p, CostFunctionBasePointer & cost, itk::Array< double > & lowerBounds, itk::Array< double > & upperBounds) protected
Performs an optimization of the supplied cost function and parameters using the specified optimizer(s). Returns the optimized parameters.
Definition at line 1077 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SampleStickModelCompartmentsFromDTI (BaseCompartmentType * tensorCompartment, MCMPointer & complexModel, SequenceGeneratorType & generator) protected
Performs direction sampling initialization from simplified model (handles only DTI right now)
Definition at line 1221 of file animaMCMEstimatorImageFilter.hxx.
References anima::NDHaltonSequenceGenerator::GetNextSequenceValue(), anima::RecomposeTensor(), anima::TransformCartesianToSphericalCoordinates(), and anima::TransformSphericalToCartesianCoordinates().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeModelFromSimplifiedOne().
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetAbsoluteCostChange (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetAxialDiffusivityFixedValue (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetB0Threshold (double _arg) virtual
template<class InputPixelType, class OutputPixelType> void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetBValuesList (std::vector< double > & mb) inline
Definition at line 177 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetCompartmentType (CompartmentType _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetExternalDTIParameters (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetFindOptimalNumberOfCompartments (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetFreeWaterProportionFixedValue (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetGTolerance (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetMaxEval (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetMLEstimationStrategy (MaximumLikelihoodEstimationMode _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetModelWithFreeWaterComponent (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetModelWithRestrictedWaterComponent (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetModelWithStationaryWaterComponent (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetMoseVolume (MoseImageType * img) inline
Definition at line 230 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetNoiseType (SignalNoiseType _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetNumberOfCoils (unsigned int _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetNumberOfCompartments (unsigned int _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetNumberOfRandomRestarts (unsigned int _arg) virtual
template<class InputPixelType, class OutputPixelType> void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetOptimizer (std::string & opt) inline
Definition at line 182 of file animaMCMEstimatorImageFilter.h.
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetRadialDiffusivity1FixedValue (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetRadialDiffusivity2FixedValue (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetRestrictedWaterProportionFixedValue (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetStationaryWaterProportionFixedValue (double _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseCommonDiffusivities (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConcentrationBoundsFromDTI (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedDiffusivity (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedFreeWaterDiffusivity (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedIRWDiffusivity (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseFixedWeights (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetVNLDerivativeComputation (bool _arg) virtual
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetXTolerance (double _arg) virtual
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SpecificModelEstimation (MCMPointer & mcmValue, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected virtual
Perform additional estimation after ball and zeppelin if needed.
Definition at line 868 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer(), anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::NDHaltonSequenceGenerator::GetNextSequenceValue(), anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::NDHaltonSequenceGenerator::SetLowerBounds(), anima::NDHaltonSequenceGenerator::SetUpperBounds(), and anima::Tensor.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TrunkModelEstimation().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 353 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TrunkModelEstimation (MCMPointer & mcmValue, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Doing estimation, calling initialization procedure until ball and zeppelin, returns AICc value.
Definition at line 773 of file animaMCMEstimatorImageFilter.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MultiCompartmentModelCreator::SetUseConstrainedDiffusivity(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SpecificModelEstimation(), anima::Stick, and anima::Zeppelin.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput (std::string fileName)
Definition at line 80 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CheckComputationMask(), and anima::MCMFileWriter< PixelType, ImageDimension >::SetInputImage().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation().
The documentation for this class was generated from the following files:
animaMCMEstimatorImageFilter.h
animaMCMEstimatorImageFilter.hxx