ANIMA: anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
#include <animaMCMBasicMeanSquaresImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, ImageDimension > ContinuousIndexType
typedef Superclass::CoordinateRepresentationType CoordinateRepresentationType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef MCModelType::Vector3DType GradientType
typedef Superclass::InputPointType InputPointType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef TFixedImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMBasicMeanSquaresImageToImageMetric Self
typedef BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > TFixedImage
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > TMovingImage
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ParametersValueType CoordinateRepresentationType
typedef Superclass::DerivativeType DerivativeType
typedef FixedImageType::ConstPointer FixedImageConstPointer
typedef FixedImageMaskType::ConstPointer FixedImageMaskConstPointer
typedef FixedImageMaskType::Pointer FixedImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(FixedImageDimension) > FixedImageMaskType
typedef FixedImageType::RegionType FixedImageRegionType
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > FixedImageType
typedef TransformType::InputPointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< MovingImageType, CoordinateRepresentationType > InterpolatorType
typedef Superclass::MeasureType MeasureType
enum ModelReorientationType
typedef MovingImageType::ConstPointer MovingImageConstPointer
typedef MovingImageMaskType::ConstPointer MovingImageMaskConstPointer
typedef MovingImageMaskType::Pointer MovingImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(MovingImageDimension) > MovingImageMaskType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension >::PixelType MovingImagePixelType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > MovingImageType
typedef TransformType::OutputPointType OutputPointType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef double RealType
typedef BaseOrientedModelImageToImageMetric Self
typedef itk::SingleValuedCostFunction Superclass
typedef TransformType::JacobianType TransformJacobianType
typedef TransformType::ParametersType TransformParametersType
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< CoordinateRepresentationType, itkGetStaticConstMacro(MovingImageDimension), itkGetStaticConstMacro(FixedImageDimension)> TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void PreComputeFixedValues ()
virtual void SetOneToOneMapping (bool _arg)
Public Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
Should not be used.
virtual const FixedImageType * GetFixedImage () const
virtual const FixedImageMaskType * GetFixedImageMask () const
virtual const FixedImageRegionType & GetFixedImageRegion () const
virtual const InterpolatorType * GetInterpolator () const
virtual ModelReorientationType GetModelRotation () const
virtual const MovingImageType * GetMovingImage () const
virtual const MovingImageMaskType * GetMovingImageMask () const
unsigned int GetNumberOfParameters (void) const ITK_OVERRIDE
virtual const unsigned long & GetNumberOfPixelsCounted () const
virtual const TransformType * GetTransform () const
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &value, DerivativeType &derivative) const ITK_OVERRIDE
virtual void Initialize () throw (itk::ExceptionObject)
virtual void SetFixedImage (const FixedImageType *_arg)
virtual void SetFixedImageMask (FixedImageMaskType *_arg)
virtual void SetFixedImageMask (const FixedImageMaskType *_arg)
virtual void SetFixedImageRegion (FixedImageRegionType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetModelRotation (ModelReorientationType _arg)
virtual void SetMovingImage (const MovingImageType *_arg)
virtual void SetMovingImageMask (MovingImageMaskType *_arg)
virtual void SetMovingImageMask (const MovingImageMaskType *_arg)
virtual void SetTransform (TransformType *_arg)
void SetTransformParameters (const ParametersType &parameters) const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
bool CheckTensorCompatibility () const
double ComputeNonTensorBasedMetricPart (unsigned int index, const MCModelPointer &movingValue) const
double ComputeTensorBasedMetricPart (unsigned int index, const MCModelPointer &movingValue) const
bool isZero (PixelType &vector) const
MCMBasicMeanSquaresImageToImageMetric ()
virtual ~MCMBasicMeanSquaresImageToImageMetric ()
Protected Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
BaseOrientedModelImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~BaseOrientedModelImageToImageMetric ()
Additional Inherited Members
Static Public Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
static const unsigned int FixedImageDimension
static const unsigned int MovingImageDimension
Protected Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
FixedImageConstPointer m_FixedImage
FixedImageMaskConstPointer m_FixedImageMask
InterpolatorPointer m_Interpolator
MovingImageConstPointer m_MovingImage
MovingImageMaskConstPointer m_MovingImageMask
unsigned long m_NumberOfPixelsCounted
vnl_matrix< double > m_OrientationMatrix
TransformPointer m_Transform
Detailed Description
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension>
class anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >
Definition at line 11 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
Member Typedef Documentation
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<const Self> anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ConstPointer
Definition at line 22 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::ContinuousIndex<double, ImageDimension> anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ContinuousIndexType
Definition at line 42 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::CoordinateRepresentationType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CoordinateRepresentationType
Definition at line 44 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageConstPointer anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageConstPointer
Definition at line 49 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageType
Definition at line 47 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Vector3DType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GradientType
Definition at line 26 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::InputPointType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::InputPointType
Definition at line 41 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Pointer anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelPointer
Definition at line 25 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MultiCompartmentModel anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelType
Definition at line 24 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MeasureType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType
Definition at line 46 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageConstPointer anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageConstPointer
Definition at line 50 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageType
Definition at line 48 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::OutputPointType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::OutputPointType
Definition at line 40 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef TFixedImage::PixelType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PixelType
Types transferred from the base class
Definition at line 35 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<Self> anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Pointer
Definition at line 21 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCMBasicMeanSquaresImageToImageMetric anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Self
Definition at line 19 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef BaseOrientedModelImageToImageMetric<TFixedImage, TMovingImage > anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Superclass
Definition at line 20 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TFixedImage
Standard class typedefs.
Definition at line 16 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TMovingImage
Definition at line 17 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformParametersType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformParametersType
Definition at line 39 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformPointer anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformPointer
Definition at line 38 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformType
Definition at line 37 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
Constructor & Destructor Documentation
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMBasicMeanSquaresImageToImageMetric () protected
Definition at line 16 of file animaMCMBasicMeanSquaresImageToImageMetric.hxx.
References anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), and anima::MultiCompartmentModelCreator::SetStationaryWaterProportionFixedValue().
Referenced by anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMBasicMeanSquaresImageToImageMetric().
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMBasicMeanSquaresImageToImageMetric () inline protected virtual
Definition at line 61 of file animaMCMBasicMeanSquaresImageToImageMetric.h.
References anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart(), anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart(), anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero(), and anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMBasicMeanSquaresImageToImageMetric().
Member Function Documentation
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility () const protected
Definition at line 36 of file animaMCMBasicMeanSquaresImageToImageMetric.hxx.
References anima::DDI, and anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
Referenced by anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMBasicMeanSquaresImageToImageMetric(), and anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMBasicMeanSquaresImageToImageMetric().
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> double anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart (unsigned int index, const MCModelPointer & movingValue) const protected
Definition at line 305 of file animaMCMBasicMeanSquaresImageToImageMetric.hxx.
References anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
Referenced by anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart(), and anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMBasicMeanSquaresImageToImageMetric().
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> double anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart (unsigned int index, const MCModelPointer & movingValue) const protected
Definition at line 133 of file animaMCMBasicMeanSquaresImageToImageMetric.hxx.
References anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart(), anima::GetTensorLogarithm(), and anima::GetVectorRepresentation().
Referenced by anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), and anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMBasicMeanSquaresImageToImageMetric().
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual::itk::LightObject::Pointer anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CreateAnother (void) const
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual const char* anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >.
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Definition at line 60 of file animaMCMBasicMeanSquaresImageToImageMetric.hxx.
References anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart(), and PPD.
Referenced by anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility().
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero (PixelType & vector) const protected
Definition at line 314 of file animaMCMBasicMeanSquaresImageToImageMetric.hxx.
References anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues().
Referenced by anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart(), and anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMBasicMeanSquaresImageToImageMetric().
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> static Pointer anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::New () static
Method for creation through the object factory.
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues ()
Definition at line 330 of file animaMCMBasicMeanSquaresImageToImageMetric.hxx.
Referenced by anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual void anima::MCMBasicMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetOneToOneMapping (bool _arg) virtual
The documentation for this class was generated from the following files:
animaMCMBasicMeanSquaresImageToImageMetric.h
animaMCMBasicMeanSquaresImageToImageMetric.hxx