ANIMA: anima::FibersReader Class Reference
anima::FibersReader Class Reference
#include <animaFibersReader.h>
Public Member Functions
FibersReader ()
vtkPolyData * GetOutput ()
void SetFileName (std::string &name)
void Update ()
~FibersReader ()
Protected Member Functions
void ReadFileAsMedinriaFibers ()
void ReadFileAsVTKAscii ()
void ReadFileAsVTKXML ()
Detailed Description
Definition at line 11 of file animaFibersReader.h.
Constructor & Destructor Documentation
anima::FibersReader::FibersReader () inline
Definition at line 14 of file animaFibersReader.h.
anima::FibersReader::~FibersReader () inline
Definition at line 20 of file animaFibersReader.h.
Member Function Documentation
vtkPolyData* anima::FibersReader::GetOutput () inline
Definition at line 25 of file animaFibersReader.h.
Referenced by main().
void anima::FibersReader::ReadFileAsMedinriaFibers () protected
Definition at line 53 of file animaFibersReader.cxx.
Referenced by Update().
void anima::FibersReader::ReadFileAsVTKAscii () protected
Definition at line 33 of file animaFibersReader.cxx.
Referenced by Update().
void anima::FibersReader::ReadFileAsVTKXML () protected
Definition at line 43 of file animaFibersReader.cxx.
Referenced by Update().
void anima::FibersReader::SetFileName (std::string & name) inline
Definition at line 22 of file animaFibersReader.h.
Referenced by main().
void anima::FibersReader::Update ()
Definition at line 15 of file animaFibersReader.cxx.
References ReadFileAsMedinriaFibers(), ReadFileAsVTKAscii(), and ReadFileAsVTKXML().
Referenced by main().
The documentation for this class was generated from the following files:
animaFibersReader.h
animaFibersReader.cxx