ANIMA: anima::ConcentrationUpperBoundSolverCostFunction Class Reference
anima::ConcentrationUpperBoundSolverCostFunction Class Reference
#include <animaMCMEstimatorImageFilter.h>
Public Member Functions
double operator() (const double k)
void SetWMAxialDiffusivity (double val)
void SetWMRadialDiffusivity (double val)
Detailed Description
Definition at line 21 of file animaMCMEstimatorImageFilter.h.
Member Function Documentation
double anima::ConcentrationUpperBoundSolverCostFunction::operator() (const double k) inline
Definition at line 27 of file animaMCMEstimatorImageFilter.h.
References anima::xi().
void anima::ConcentrationUpperBoundSolverCostFunction::SetWMAxialDiffusivity (double val) inline
Definition at line 24 of file animaMCMEstimatorImageFilter.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData().
void anima::ConcentrationUpperBoundSolverCostFunction::SetWMRadialDiffusivity (double val) inline
Definition at line 25 of file animaMCMEstimatorImageFilter.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData().
The documentation for this class was generated from the following file:
animaMCMEstimatorImageFilter.h