ANIMA: anima::NDHaltonSequenceGenerator Class Reference
anima::NDHaltonSequenceGenerator Class Reference
#include <animaNDHaltonSequenceGenerator.h>
Public Member Functions
std::vector< double > & GetNextSequenceValue ()
NDHaltonSequenceGenerator (unsigned int numDimensions)
void SetLowerBounds (std::vector< double > &lb)
void SetUpperBounds (std::vector< double > &ub)
virtual ~NDHaltonSequenceGenerator ()
Detailed Description
Definition at line 9 of file animaNDHaltonSequenceGenerator.h.
Constructor & Destructor Documentation
anima::NDHaltonSequenceGenerator::NDHaltonSequenceGenerator (unsigned int numDimensions)
Definition at line 10 of file animaNDHaltonSequenceGenerator.cxx.
virtual anima::NDHaltonSequenceGenerator::~NDHaltonSequenceGenerator () inline virtual
Definition at line 13 of file animaNDHaltonSequenceGenerator.h.
Member Function Documentation
std::vector< double > & anima::NDHaltonSequenceGenerator::GetNextSequenceValue ()
Definition at line 26 of file animaNDHaltonSequenceGenerator.cxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SampleStickModelCompartmentsFromDTI(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SpecificModelEstimation().
void anima::NDHaltonSequenceGenerator::SetLowerBounds (std::vector< double > & lb) inline
Definition at line 15 of file animaNDHaltonSequenceGenerator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SpecificModelEstimation().
void anima::NDHaltonSequenceGenerator::SetUpperBounds (std::vector< double > & ub) inline
Definition at line 16 of file animaNDHaltonSequenceGenerator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SpecificModelEstimation().
The documentation for this class was generated from the following files:
animaNDHaltonSequenceGenerator.h
animaNDHaltonSequenceGenerator.cxx