ANIMA: anima::mcm_utilities Namespace Reference
anima::mcm_utilities Namespace Reference
Functions
double BoundedDerivativeAddOn (double x, double inputSign, double lowerBound, double upperBound)
double ComputeBoundedValue (double x, double &inputSign, double lowerBound, double upperBound)
double UnboundValue (double x, double lowerBound, double upperBound)
Function Documentation
ANIMAMCMBASE_EXPORT double anima::mcm_utilities::BoundedDerivativeAddOn (double x, double inputSign, double lowerBound, double upperBound)
Definition at line 34 of file animaBaseCompartment.cxx.
References anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DefaultConcentrationUpperBound, anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_Epsilon, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_RadialDiffusivityUpperBound, and anima::BaseCompartment::m_ZeroLowerBound.
Referenced by anima::FreeWaterCompartment::GetAxialDiffusivityDerivativeFactor(), anima::IsotropicRestrictedWaterCompartment::GetAxialDiffusivityDerivativeFactor(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::TensorCompartment::GetSignalAttenuationJacobian(), and anima::ZeppelinCompartment::GetSignalAttenuationJacobian().
ANIMAMCMBASE_EXPORT double anima::mcm_utilities::ComputeBoundedValue (double x, double & inputSign, double lowerBound, double upperBound)
Definition at line 22 of file animaBaseCompartment.cxx.
Referenced by anima::FreeWaterCompartment::BoundParameters(), anima::IsotropicRestrictedWaterCompartment::BoundParameters(), anima::StickCompartment::BoundParameters(), anima::ZeppelinCompartment::BoundParameters(), and anima::TensorCompartment::BoundParameters().
ANIMAMCMBASE_EXPORT double anima::mcm_utilities::UnboundValue (double x, double lowerBound, double upperBound)
Definition at line 12 of file animaBaseCompartment.cxx.
Referenced by anima::FreeWaterCompartment::UnboundParameters(), anima::IsotropicRestrictedWaterCompartment::UnboundParameters(), anima::StickCompartment::UnboundParameters(), anima::ZeppelinCompartment::UnboundParameters(), and anima::TensorCompartment::UnboundParameters().